// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated by gen.go; DO NOT EDIT.

package mondoogql

// APITokenOrderField
type APITokenOrderField string

const (
	APITokenOrderFieldName      APITokenOrderField = "NAME"
	APITokenOrderFieldLastUsed  APITokenOrderField = "LAST_USED"
	APITokenOrderFieldCreatedAt APITokenOrderField = "CREATED_AT"
)

// Access
type Access string

const (
	AccessAll           Access = "ALL"
	AccessPublic        Access = "PUBLIC"
	AccessAuthenticated Access = "AUTHENTICATED"
	AccessPrivate       Access = "PRIVATE"
)

// ActionType
type ActionType string

const (
	ActionTypeRetrySetup     ActionType = "RETRY_SETUP"
	ActionTypeRunScan        ActionType = "RUN_SCAN"
	ActionTypeRunExport      ActionType = "RUN_EXPORT"
	ActionTypePause          ActionType = "PAUSE"
	ActionTypeUnpause        ActionType = "UNPAUSE"
	ActionTypeMetrics        ActionType = "METRICS"
	ActionTypeUpdate         ActionType = "UPDATE"
	ActionTypeDiagnostics    ActionType = "DIAGNOSTICS"
	ActionTypeClearScanQueue ActionType = "CLEAR_SCAN_QUEUE"
)

// AdvisoryOrderField
type AdvisoryOrderField string

const (
	AdvisoryOrderFieldID        AdvisoryOrderField = "ID"
	AdvisoryOrderFieldTitle     AdvisoryOrderField = "TITLE"
	AdvisoryOrderFieldPublished AdvisoryOrderField = "PUBLISHED"
	AdvisoryOrderFieldScore     AdvisoryOrderField = "SCORE"
)

// AdvisoryPlatformFilter
type AdvisoryPlatformFilter string

const (
	AdvisoryPlatformFilterRedhat AdvisoryPlatformFilter = "REDHAT"
	AdvisoryPlatformFilterAmazon AdvisoryPlatformFilter = "AMAZON"
	AdvisoryPlatformFilterDebian AdvisoryPlatformFilter = "DEBIAN"
	AdvisoryPlatformFilterUbuntu AdvisoryPlatformFilter = "UBUNTU"
	AdvisoryPlatformFilterAlpine AdvisoryPlatformFilter = "ALPINE"
	AdvisoryPlatformFilterOracle AdvisoryPlatformFilter = "ORACLE"
	AdvisoryPlatformFilterSuse   AdvisoryPlatformFilter = "SUSE"
)

// AdvisorySummaryOrderField
type AdvisorySummaryOrderField string

const (
	AdvisorySummaryOrderFieldID          AdvisorySummaryOrderField = "ID"
	AdvisorySummaryOrderFieldTitle       AdvisorySummaryOrderField = "TITLE"
	AdvisorySummaryOrderFieldPublished   AdvisorySummaryOrderField = "PUBLISHED"
	AdvisorySummaryOrderFieldScore       AdvisorySummaryOrderField = "SCORE"
	AdvisorySummaryOrderFieldRiskfactors AdvisorySummaryOrderField = "RISKFACTORS"
)

// AgentOrderField
type AgentOrderField string

const (
	AgentOrderFieldID          AgentOrderField = "ID"
	AgentOrderFieldName        AgentOrderField = "NAME"
	AgentOrderFieldPlatform    AgentOrderField = "PLATFORM"
	AgentOrderFieldIP          AgentOrderField = "IP"
	AgentOrderFieldVersion     AgentOrderField = "VERSION"
	AgentOrderFieldStatus      AgentOrderField = "STATUS"
	AgentOrderFieldLastCheckin AgentOrderField = "LAST_CHECKIN"
	AgentOrderFieldHostname    AgentOrderField = "HOSTNAME"
)

// AgentState
type AgentState string

const (
	AgentStateActive  AgentState = "ACTIVE"
	AgentStateMissing AgentState = "MISSING"
)

// AggregateScoreOrderField
type AggregateScoreOrderField string

const (
	AggregateScoreOrderFieldRiskScore   AggregateScoreOrderField = "RISK_SCORE"
	AggregateScoreOrderFieldRank        AggregateScoreOrderField = "RANK"
	AggregateScoreOrderFieldBlastRadius AggregateScoreOrderField = "BLAST_RADIUS"
	AggregateScoreOrderFieldTitle       AggregateScoreOrderField = "TITLE"
)

// AggregateScoreType
type AggregateScoreType string

const (
	AggregateScoreTypeVulnerability AggregateScoreType = "VULNERABILITY"
	AggregateScoreTypeAdvisory      AggregateScoreType = "ADVISORY"
	AggregateScoreTypeCheck         AggregateScoreType = "CHECK"
	AggregateScoreTypePolicy        AggregateScoreType = "POLICY"
	AggregateScoreTypeRisk          AggregateScoreType = "RISK"
	AggregateScoreTypeAsset         AggregateScoreType = "ASSET"
	AggregateScoreTypeOther         AggregateScoreType = "OTHER"
)

// AssetLinkType
type AssetLinkType string

const (
	AssetLinkTypeFleet AssetLinkType = "FLEET"
	AssetLinkTypeCi    AssetLinkType = "CI"
)

// AssetOrderField
type AssetOrderField string

const (
	AssetOrderFieldID          AssetOrderField = "ID"
	AssetOrderFieldName        AssetOrderField = "NAME"
	AssetOrderFieldPlatform    AssetOrderField = "PLATFORM"
	AssetOrderFieldScore       AssetOrderField = "SCORE"
	AssetOrderFieldLastUpdated AssetOrderField = "LAST_UPDATED"
)

// AssetOverviewReferenceTypeEnum
type AssetOverviewReferenceTypeEnum string

const (
	AssetOverviewReferenceTypeEnumAsset       AssetOverviewReferenceTypeEnum = "ASSET"
	AssetOverviewReferenceTypeEnumIntegration AssetOverviewReferenceTypeEnum = "INTEGRATION"
)

// AssetReportQueryOrderField
type AssetReportQueryOrderField string

const (
	AssetReportQueryOrderFieldSeverity AssetReportQueryOrderField = "SEVERITY"
	AssetReportQueryOrderFieldTitle    AssetReportQueryOrderField = "TITLE"
	AssetReportQueryOrderFieldScore    AssetReportQueryOrderField = "SCORE"
)

// AssetSearchOrderField
type AssetSearchOrderField string

const (
	AssetSearchOrderFieldID   AssetSearchOrderField = "ID"
	AssetSearchOrderFieldName AssetSearchOrderField = "NAME"
)

// AssetState
type AssetState string

const (
	AssetStateUnknown    AssetState = "UNKNOWN"
	AssetStateError      AssetState = "ERROR"
	AssetStateDeleted    AssetState = "DELETED"
	AssetStatePending    AssetState = "PENDING"
	AssetStateRunning    AssetState = "RUNNING"
	AssetStateStopping   AssetState = "STOPPING"
	AssetStateStopped    AssetState = "STOPPED"
	AssetStateShutdown   AssetState = "SHUTDOWN"
	AssetStateTerminated AssetState = "TERMINATED"
	AssetStateReboot     AssetState = "REBOOT"
	AssetStateOnline     AssetState = "ONLINE"
	AssetStateOffline    AssetState = "OFFLINE"
)

// AssetSummaryOrderField
type AssetSummaryOrderField string

const (
	AssetSummaryOrderFieldID        AssetSummaryOrderField = "ID"
	AssetSummaryOrderFieldTitle     AssetSummaryOrderField = "TITLE"
	AssetSummaryOrderFieldPublished AssetSummaryOrderField = "PUBLISHED"
	AssetSummaryOrderFieldModified  AssetSummaryOrderField = "MODIFIED"
	AssetSummaryOrderFieldScore     AssetSummaryOrderField = "SCORE"
)

// AssetUrlStatsScope
type AssetUrlStatsScope string

const (
	AssetUrlStatsScopeAll             AssetUrlStatsScope = "ALL"
	AssetUrlStatsScopeVulnerabilities AssetUrlStatsScope = "VULNERABILITIES"
	AssetUrlStatsScopeSecurity        AssetUrlStatsScope = "SECURITY"
)

// AuditLogOrderField
type AuditLogOrderField string

const (
	AuditLogOrderFieldTimestamp AuditLogOrderField = "TIMESTAMP"
)

// BucketOutputType
type BucketOutputType string

const (
	BucketOutputTypeUnknown BucketOutputType = "UNKNOWN"
	BucketOutputTypeCsv     BucketOutputType = "CSV"
	BucketOutputTypeJsonl   BucketOutputType = "JSONL"
)

// CatalogType
type CatalogType string

const (
	CatalogTypeAll       CatalogType = "ALL"
	CatalogTypePolicy    CatalogType = "POLICY"
	CatalogTypeQuerypack CatalogType = "QUERYPACK"
	CatalogTypeQuery     CatalogType = "QUERY"
)

// CheckState
type CheckState string

const (
	CheckStateActive   CheckState = "ACTIVE"
	CheckStateSnoozed  CheckState = "SNOOZED"
	CheckStateDisabled CheckState = "DISABLED"
)

// ChecksOrderField
type ChecksOrderField string

const (
	ChecksOrderFieldAssetsCount ChecksOrderField = "ASSETS_COUNT"
	ChecksOrderFieldName        ChecksOrderField = "NAME"
	ChecksOrderFieldCompletion  ChecksOrderField = "COMPLETION"
)

// CicdProjectOrderField
type CicdProjectOrderField string

const (
	CicdProjectOrderFieldName CicdProjectOrderField = "NAME"
)

// ClientIntegrationType
type ClientIntegrationType string

const (
	ClientIntegrationTypeUnknown          ClientIntegrationType = "UNKNOWN"
	ClientIntegrationTypeK8s              ClientIntegrationType = "K8S"
	ClientIntegrationTypeAws              ClientIntegrationType = "AWS"
	ClientIntegrationTypeManagedClient    ClientIntegrationType = "MANAGED_CLIENT"
	ClientIntegrationTypeAzure            ClientIntegrationType = "AZURE"
	ClientIntegrationTypeMs365            ClientIntegrationType = "MS365"
	ClientIntegrationTypeGcp              ClientIntegrationType = "GCP"
	ClientIntegrationTypeGoogleWorkspace  ClientIntegrationType = "GOOGLE_WORKSPACE"
	ClientIntegrationTypeOkta             ClientIntegrationType = "OKTA"
	ClientIntegrationTypeBigquery         ClientIntegrationType = "BIGQUERY"
	ClientIntegrationTypeSnowflake        ClientIntegrationType = "SNOWFLAKE"
	ClientIntegrationTypeAwsS3            ClientIntegrationType = "AWS_S3"
	ClientIntegrationTypeS3               ClientIntegrationType = "S3"
	ClientIntegrationTypeHostedSlack      ClientIntegrationType = "HOSTED_SLACK"
	ClientIntegrationTypeGitHub           ClientIntegrationType = "GITHUB"
	ClientIntegrationTypeGitLab           ClientIntegrationType = "GITLAB"
	ClientIntegrationTypeGcsBucket        ClientIntegrationType = "GCS_BUCKET"
	ClientIntegrationTypePostgres         ClientIntegrationType = "POSTGRES"
	ClientIntegrationTypeOci              ClientIntegrationType = "OCI"
	ClientIntegrationTypeTicketSystemJira ClientIntegrationType = "TICKET_SYSTEM_JIRA"
	ClientIntegrationTypeAwsHosted        ClientIntegrationType = "AWS_HOSTED"
	ClientIntegrationTypeAzureBlob        ClientIntegrationType = "AZURE_BLOB"
	ClientIntegrationTypeHost             ClientIntegrationType = "HOST"
)

// ComparisonOperator
type ComparisonOperator string

const (
	ComparisonOperatorGt ComparisonOperator = "GT"
	ComparisonOperatorLt ComparisonOperator = "LT"
)

// ComplianceAssetOrderField
type ComplianceAssetOrderField string

const (
	ComplianceAssetOrderFieldID          ComplianceAssetOrderField = "ID"
	ComplianceAssetOrderFieldName        ComplianceAssetOrderField = "NAME"
	ComplianceAssetOrderFieldPlatform    ComplianceAssetOrderField = "PLATFORM"
	ComplianceAssetOrderFieldCompletion  ComplianceAssetOrderField = "COMPLETION"
	ComplianceAssetOrderFieldLastUpdated ComplianceAssetOrderField = "LAST_UPDATED"
)

// ComplianceFrameworkMutationAction
type ComplianceFrameworkMutationAction string

const (
	ComplianceFrameworkMutationActionEnable  ComplianceFrameworkMutationAction = "ENABLE"
	ComplianceFrameworkMutationActionPreview ComplianceFrameworkMutationAction = "PREVIEW"
)

// ComplianceFrameworkState
type ComplianceFrameworkState string

const (
	ComplianceFrameworkStateActive  ComplianceFrameworkState = "ACTIVE"
	ComplianceFrameworkStatePreview ComplianceFrameworkState = "PREVIEW"
)

// ContentSearchResultItemOrderField
type ContentSearchResultItemOrderField string

const (
	ContentSearchResultItemOrderFieldName ContentSearchResultItemOrderField = "NAME"
)

// ControlState
type ControlState string

const (
	ControlStateActive     ControlState = "ACTIVE"
	ControlStateSnoozed    ControlState = "SNOOZED"
	ControlStateDisabled   ControlState = "DISABLED"
	ControlStateOutOfScope ControlState = "OUT_OF_SCOPE"
)

// ControlsOrderField
type ControlsOrderField string

const (
	ControlsOrderFieldID         ControlsOrderField = "ID"
	ControlsOrderFieldTitle      ControlsOrderField = "TITLE"
	ControlsOrderFieldCompletion ControlsOrderField = "COMPLETION"
	ControlsOrderFieldChecks     ControlsOrderField = "CHECKS"
	ControlsOrderFieldAssets     ControlsOrderField = "ASSETS"
	ControlsOrderFieldExceptions ControlsOrderField = "EXCEPTIONS"
)

// CveOrderField
type CveOrderField string

const (
	CveOrderFieldID        CveOrderField = "ID"
	CveOrderFieldTitle     CveOrderField = "TITLE"
	CveOrderFieldPublished CveOrderField = "PUBLISHED"
	CveOrderFieldModified  CveOrderField = "MODIFIED"
	CveOrderFieldScore     CveOrderField = "SCORE"
)

// CveState
type CveState string

const (
	CveStateInvalid    CveState = "INVALID"
	CveStatePublic     CveState = "PUBLIC"
	CveStateReserved   CveState = "RESERVED"
	CveStateReplacedBy CveState = "REPLACED_BY"
	CveStateSplitFrom  CveState = "SPLIT_FROM"
	CveStateMergedTo   CveState = "MERGED_TO"
)

// CveSummaryOrderField
type CveSummaryOrderField string

const (
	CveSummaryOrderFieldID          CveSummaryOrderField = "ID"
	CveSummaryOrderFieldTitle       CveSummaryOrderField = "TITLE"
	CveSummaryOrderFieldPublished   CveSummaryOrderField = "PUBLISHED"
	CveSummaryOrderFieldModified    CveSummaryOrderField = "MODIFIED"
	CveSummaryOrderFieldScore       CveSummaryOrderField = "SCORE"
	CveSummaryOrderFieldRiskfactors CveSummaryOrderField = "RISKFACTORS"
)

// DocumentFormat
type DocumentFormat string

const (
	DocumentFormatPdf DocumentFormat = "PDF"
)

// DocumentStatus
type DocumentStatus string

const (
	DocumentStatusQueued    DocumentStatus = "QUEUED"
	DocumentStatusRunning   DocumentStatus = "RUNNING"
	DocumentStatusCompleted DocumentStatus = "COMPLETED"
	DocumentStatusFailed    DocumentStatus = "FAILED"
)

// DocumentType
type DocumentType string

const (
	DocumentTypeFrameworkReport DocumentType = "FRAMEWORK_REPORT"
	DocumentTypeControlReport   DocumentType = "CONTROL_REPORT"
)

// EOLStatus
type EOLStatus string

const (
	EOLStatusScheduled EOLStatus = "SCHEDULED"
	EOLStatusEol       EOLStatus = "EOL"
)

// EmailPreferenceList
type EmailPreferenceList string

const (
	EmailPreferenceListNewsletterGeneral         EmailPreferenceList = "NEWSLETTER_GENERAL"
	EmailPreferenceListNewsletterProduct         EmailPreferenceList = "NEWSLETTER_PRODUCT"
	EmailPreferenceListNewsletterEvents          EmailPreferenceList = "NEWSLETTER_EVENTS"
	EmailPreferenceListNotificationWeeklyReports EmailPreferenceList = "NOTIFICATION_WEEKLY_REPORTS"
	EmailPreferenceListNotificationSpaceAlerts   EmailPreferenceList = "NOTIFICATION_SPACE_ALERTS"
)

// ExceptionMutationAction
type ExceptionMutationAction string

const (
	ExceptionMutationActionEnable     ExceptionMutationAction = "ENABLE"
	ExceptionMutationActionDisable    ExceptionMutationAction = "DISABLE"
	ExceptionMutationActionSnooze     ExceptionMutationAction = "SNOOZE"
	ExceptionMutationActionOutOfScope ExceptionMutationAction = "OUT_OF_SCOPE"
)

// ExceptionReviewAction
type ExceptionReviewAction string

const (
	ExceptionReviewActionApproved ExceptionReviewAction = "APPROVED"
	ExceptionReviewActionRejected ExceptionReviewAction = "REJECTED"
)

// ExceptionType
type ExceptionType string

const (
	ExceptionTypeCompliance ExceptionType = "COMPLIANCE"
	ExceptionTypeSecurity   ExceptionType = "SECURITY"
)

// FormatType
type FormatType string

const (
	FormatTypeJSON FormatType = "JSON"
	FormatTypeCsv  FormatType = "CSV"
)

// GitPipelineKind
type GitPipelineKind string

const (
	GitPipelineKindPullRequest GitPipelineKind = "PULL_REQUEST"
	GitPipelineKindBranch      GitPipelineKind = "BRANCH"
	GitPipelineKindTag         GitPipelineKind = "TAG"
	GitPipelineKindUnknown     GitPipelineKind = "UNKNOWN"
)

// GithubIntegrationType
type GithubIntegrationType string

const (
	GithubIntegrationTypeRepo GithubIntegrationType = "REPO"
	GithubIntegrationTypeOrg  GithubIntegrationType = "ORG"
)

// GitlabIntegrationType
type GitlabIntegrationType string

const (
	GitlabIntegrationTypeGroup GitlabIntegrationType = "GROUP"
	GitlabIntegrationTypeNone  GitlabIntegrationType = "NONE"
)

// Grade
type Grade string

const (
	GradeA Grade = "A"
	GradeB Grade = "B"
	GradeC Grade = "C"
	GradeD Grade = "D"
	GradeF Grade = "F"
	GradeU Grade = "U"
)

// ICON_IDS
type ICON_IDS string

const (
	ICON_IDSDefault                   ICON_IDS = "DEFAULT"
	ICON_IDSAix                       ICON_IDS = "AIX"
	ICON_IDSAtlassian                 ICON_IDS = "ATLASSIAN"
	ICON_IDSArista                    ICON_IDS = "ARISTA"
	ICON_IDSArch                      ICON_IDS = "ARCH"
	ICON_IDSManjaro                   ICON_IDS = "MANJARO"
	ICON_IDSEquinix                   ICON_IDS = "EQUINIX"
	ICON_IDSIpmi                      ICON_IDS = "IPMI"
	ICON_IDSOpcua                     ICON_IDS = "OPCUA"
	ICON_IDSVcd                       ICON_IDS = "VCD"
	ICON_IDSRaspbian                  ICON_IDS = "RASPBIAN"
	ICON_IDSKali                      ICON_IDS = "KALI"
	ICON_IDSPop                       ICON_IDS = "POP"
	ICON_IDSEuroLinux                 ICON_IDS = "EURO_LINUX"
	ICON_IDSRockyLinux                ICON_IDS = "ROCKY_LINUX"
	ICON_IDSAlmaLinux                 ICON_IDS = "ALMA_LINUX"
	ICON_IDSScientificLinux           ICON_IDS = "SCIENTIFIC_LINUX"
	ICON_IDSWrLinux                   ICON_IDS = "WR_LINUX"
	ICON_IDSGentoo                    ICON_IDS = "GENTOO"
	ICON_IDSUbios                     ICON_IDS = "UBIOS"
	ICON_IDSBusybox                   ICON_IDS = "BUSYBOX"
	ICON_IDSOpenwrt                   ICON_IDS = "OPENWRT"
	ICON_IDSAws                       ICON_IDS = "AWS"
	ICON_IDSAzure                     ICON_IDS = "AZURE"
	ICON_IDSGcp                       ICON_IDS = "GCP"
	ICON_IDSK8s                       ICON_IDS = "K8S"
	ICON_IDSTerraform                 ICON_IDS = "TERRAFORM"
	ICON_IDSGitHub                    ICON_IDS = "GITHUB"
	ICON_IDSGitLab                    ICON_IDS = "GITLAB"
	ICON_IDSOkta                      ICON_IDS = "OKTA"
	ICON_IDSGoogleWorkspace           ICON_IDS = "GOOGLE_WORKSPACE"
	ICON_IDSMacos                     ICON_IDS = "MACOS"
	ICON_IDSSlack                     ICON_IDS = "SLACK"
	ICON_IDSWindows                   ICON_IDS = "WINDOWS"
	ICON_IDSMs365                     ICON_IDS = "MS365"
	ICON_IDSDNS                       ICON_IDS = "DNS"
	ICON_IDSOci                       ICON_IDS = "OCI"
	ICON_IDSRedhat                    ICON_IDS = "REDHAT"
	ICON_IDSAmazon                    ICON_IDS = "AMAZON"
	ICON_IDSDebian                    ICON_IDS = "DEBIAN"
	ICON_IDSUbuntu                    ICON_IDS = "UBUNTU"
	ICON_IDSAlpine                    ICON_IDS = "ALPINE"
	ICON_IDSOracle                    ICON_IDS = "ORACLE"
	ICON_IDSSuse                      ICON_IDS = "SUSE"
	ICON_IDSMicrosoft                 ICON_IDS = "MICROSOFT"
	ICON_IDSMicrosoftEdge             ICON_IDS = "MICROSOFT_EDGE"
	ICON_IDSMicrosoftVisualStudioCode ICON_IDS = "MICROSOFT_VISUAL_STUDIO_CODE"
	ICON_IDSMicrosoftDotnet           ICON_IDS = "MICROSOFT_DOTNET"
	ICON_IDSLinux                     ICON_IDS = "LINUX"
	ICON_IDSLinuxMint                 ICON_IDS = "LINUX_MINT"
	ICON_IDSFedora                    ICON_IDS = "FEDORA"
	ICON_IDSCentos                    ICON_IDS = "CENTOS"
	ICON_IDSVmware                    ICON_IDS = "VMWARE"
	ICON_IDSVmwarePhoton              ICON_IDS = "VMWARE_PHOTON"
	ICON_IDSMozilla                   ICON_IDS = "MOZILLA"
	ICON_IDSGoogleChrome              ICON_IDS = "GOOGLE_CHROME"
	ICON_IDSMozillaFirefox            ICON_IDS = "MOZILLA_FIREFOX"
	ICON_IDSCve                       ICON_IDS = "CVE"
	ICON_IDSPolicy                    ICON_IDS = "POLICY"
	ICON_IDSCheck                     ICON_IDS = "CHECK"
	ICON_IDSOther                     ICON_IDS = "OTHER"
	ICON_IDSRisk                      ICON_IDS = "RISK"
	ICON_IDSAsset                     ICON_IDS = "ASSET"
)

// IntegrationMessageStatus
type IntegrationMessageStatus string

const (
	IntegrationMessageStatusInfo    IntegrationMessageStatus = "INFO"
	IntegrationMessageStatusWarning IntegrationMessageStatus = "WARNING"
	IntegrationMessageStatusError   IntegrationMessageStatus = "ERROR"
)

// IntegrationType
type IntegrationType string

const (
	IntegrationTypeUnknown          IntegrationType = "UNKNOWN"
	IntegrationTypeManagedClient    IntegrationType = "MANAGED_CLIENT"
	IntegrationTypeK8s              IntegrationType = "K8S"
	IntegrationTypeAws              IntegrationType = "AWS"
	IntegrationTypeAzure            IntegrationType = "AZURE"
	IntegrationTypeMs365            IntegrationType = "MS365"
	IntegrationTypeSlack            IntegrationType = "SLACK"
	IntegrationTypeMsteams          IntegrationType = "MSTEAMS"
	IntegrationTypeTelegram         IntegrationType = "TELEGRAM"
	IntegrationTypeHttppost         IntegrationType = "HTTPPOST"
	IntegrationTypeGcp              IntegrationType = "GCP"
	IntegrationTypeGoogleWorkspace  IntegrationType = "GOOGLE_WORKSPACE"
	IntegrationTypeOkta             IntegrationType = "OKTA"
	IntegrationTypeBigquery         IntegrationType = "BIGQUERY"
	IntegrationTypeSnowflake        IntegrationType = "SNOWFLAKE"
	IntegrationTypeAwsS3            IntegrationType = "AWS_S3"
	IntegrationTypeS3               IntegrationType = "S3"
	IntegrationTypeHostedSlack      IntegrationType = "HOSTED_SLACK"
	IntegrationTypeGitHub           IntegrationType = "GITHUB"
	IntegrationTypeGitLab           IntegrationType = "GITLAB"
	IntegrationTypeGcsBucket        IntegrationType = "GCS_BUCKET"
	IntegrationTypePostgres         IntegrationType = "POSTGRES"
	IntegrationTypeOci              IntegrationType = "OCI"
	IntegrationTypeTicketSystemJira IntegrationType = "TICKET_SYSTEM_JIRA"
	IntegrationTypeAzureBlob        IntegrationType = "AZURE_BLOB"
	IntegrationTypeHost             IntegrationType = "HOST"
	IntegrationTypeAwsHosted        IntegrationType = "AWS_HOSTED"
)

// InvitationOrderField
type InvitationOrderField string

const (
	InvitationOrderFieldCreated InvitationOrderField = "CREATED"
)

// InvitationState
type InvitationState string

const (
	InvitationStatePending  InvitationState = "PENDING"
	InvitationStateAccepted InvitationState = "ACCEPTED"
	InvitationStateDeclined InvitationState = "DECLINED"
	InvitationStateCanceled InvitationState = "CANCELED"
)

// JiraTicketContextType
type JiraTicketContextType string

const (
	JiraTicketContextTypeProjects JiraTicketContextType = "PROJECTS"
	JiraTicketContextTypeUsers    JiraTicketContextType = "USERS"
)

// K8sScanNodesStyle
type K8sScanNodesStyle string

const (
	K8sScanNodesStyleUnknown    K8sScanNodesStyle = "UNKNOWN"
	K8sScanNodesStyleCronjob    K8sScanNodesStyle = "CRONJOB"
	K8sScanNodesStyleDeployment K8sScanNodesStyle = "DEPLOYMENT"
)

// LibraryItemType
type LibraryItemType string

const (
	LibraryItemTypeAdvisory LibraryItemType = "ADVISORY"
	LibraryItemTypeCve      LibraryItemType = "CVE"
	LibraryItemTypeExploit  LibraryItemType = "EXPLOIT"
)

// LibraryOrderField
type LibraryOrderField string

const (
	LibraryOrderFieldID        LibraryOrderField = "ID"
	LibraryOrderFieldTitle     LibraryOrderField = "TITLE"
	LibraryOrderFieldPublished LibraryOrderField = "PUBLISHED"
	LibraryOrderFieldModified  LibraryOrderField = "MODIFIED"
	LibraryOrderFieldScore     LibraryOrderField = "SCORE"
)

// LibraryQueryResolution
type LibraryQueryResolution string

const (
	LibraryQueryResolutionYear  LibraryQueryResolution = "YEAR"
	LibraryQueryResolutionMonth LibraryQueryResolution = "MONTH"
)

// MembershipOrderField
type MembershipOrderField string

const (
	MembershipOrderFieldName MembershipOrderField = "NAME"
)

// MqueryAssetDataFormat
type MqueryAssetDataFormat string

const (
	MqueryAssetDataFormatJSON MqueryAssetDataFormat = "JSON"
)

// MqueryState
type MqueryState string

const (
	MqueryStateEnabled  MqueryState = "ENABLED"
	MqueryStateDisabled MqueryState = "DISABLED"
	MqueryStateIgnored  MqueryState = "IGNORED"
	MqueryStateSnoozed  MqueryState = "SNOOZED"
)

// MqueryType
type MqueryType string

const (
	MqueryTypeData    MqueryType = "DATA"
	MqueryTypeScoring MqueryType = "SCORING"
)

// OrderDirection
type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

// PackageManager
type PackageManager string

const (
	PackageManagerDpkg       PackageManager = "DPKG"
	PackageManagerYum        PackageManager = "YUM"
	PackageManagerDnf        PackageManager = "DNF"
	PackageManagerZypper     PackageManager = "ZYPPER"
	PackageManagerPowershell PackageManager = "POWERSHELL"
)

// PackageType
type PackageType string

const (
	PackageTypeOsPackage   PackageType = "OS_PACKAGE"
	PackageTypeApplication PackageType = "APPLICATION"
)

// PackagesOrderField
type PackagesOrderField string

const (
	PackagesOrderFieldName        PackagesOrderField = "NAME"
	PackagesOrderFieldScore       PackagesOrderField = "SCORE"
	PackagesOrderFieldFirstFound  PackagesOrderField = "FIRST_FOUND"
	PackagesOrderFieldRiskFactors PackagesOrderField = "RISK_FACTORS"
)

// PlatformKind
type PlatformKind string

const (
	PlatformKindUnknown             PlatformKind = "UNKNOWN"
	PlatformKindVirtualMachineImage PlatformKind = "VIRTUAL_MACHINE_IMAGE"
	PlatformKindContainerImage      PlatformKind = "CONTAINER_IMAGE"
	PlatformKindCode                PlatformKind = "CODE"
	PlatformKindPackage             PlatformKind = "PACKAGE"
	PlatformKindVirtualMachine      PlatformKind = "VIRTUAL_MACHINE"
	PlatformKindContainer           PlatformKind = "CONTAINER"
	PlatformKindProcess             PlatformKind = "PROCESS"
	PlatformKindAPI                 PlatformKind = "API"
	PlatformKindBareMetal           PlatformKind = "BARE_METAL"
)

// PolicyAction
type PolicyAction string

const (
	PolicyActionActive PolicyAction = "ACTIVE"
	PolicyActionIgnore PolicyAction = "IGNORE"
)

// PolicyReportEntryState
type PolicyReportEntryState string

const (
	PolicyReportEntryStatePass   PolicyReportEntryState = "PASS"
	PolicyReportEntryStateFail   PolicyReportEntryState = "FAIL"
	PolicyReportEntryStateIgnore PolicyReportEntryState = "IGNORE"
	PolicyReportEntryStateError  PolicyReportEntryState = "ERROR"
)

// PolicyReportMquerySummaryOrderField
type PolicyReportMquerySummaryOrderField string

const (
	PolicyReportMquerySummaryOrderFieldID          PolicyReportMquerySummaryOrderField = "ID"
	PolicyReportMquerySummaryOrderFieldName        PolicyReportMquerySummaryOrderField = "NAME"
	PolicyReportMquerySummaryOrderFieldTitle       PolicyReportMquerySummaryOrderField = "TITLE"
	PolicyReportMquerySummaryOrderFieldPlatform    PolicyReportMquerySummaryOrderField = "PLATFORM"
	PolicyReportMquerySummaryOrderFieldScore       PolicyReportMquerySummaryOrderField = "SCORE"
	PolicyReportMquerySummaryOrderFieldLastUpdated PolicyReportMquerySummaryOrderField = "LAST_UPDATED"
)

// PolicyReportScoreEntryAction
type PolicyReportScoreEntryAction string

const (
	PolicyReportScoreEntryActionUnspecified PolicyReportScoreEntryAction = "UNSPECIFIED"
	PolicyReportScoreEntryActionIgnore      PolicyReportScoreEntryAction = "IGNORE"
	PolicyReportScoreEntryActionDeactivate  PolicyReportScoreEntryAction = "DEACTIVATE"
)

// PolicyReportSummaryOrderField
type PolicyReportSummaryOrderField string

const (
	PolicyReportSummaryOrderFieldID        PolicyReportSummaryOrderField = "ID"
	PolicyReportSummaryOrderFieldTitle     PolicyReportSummaryOrderField = "TITLE"
	PolicyReportSummaryOrderFieldPublished PolicyReportSummaryOrderField = "PUBLISHED"
	PolicyReportSummaryOrderFieldModified  PolicyReportSummaryOrderField = "MODIFIED"
	PolicyReportSummaryOrderFieldScore     PolicyReportSummaryOrderField = "SCORE"
)

// PropertyQueryMutationAction
type PropertyQueryMutationAction string

const (
	PropertyQueryMutationActionSet   PropertyQueryMutationAction = "SET"
	PropertyQueryMutationActionCheck PropertyQueryMutationAction = "CHECK"
	PropertyQueryMutationActionUnset PropertyQueryMutationAction = "UNSET"
)

// RegistrationTokenOrderField
type RegistrationTokenOrderField string

const (
	RegistrationTokenOrderFieldCreated     RegistrationTokenOrderField = "CREATED"
	RegistrationTokenOrderFieldDescription RegistrationTokenOrderField = "DESCRIPTION"
	RegistrationTokenOrderFieldMrn         RegistrationTokenOrderField = "MRN"
)

// RemediationScriptType
type RemediationScriptType string

const (
	RemediationScriptTypeShell      RemediationScriptType = "SHELL"
	RemediationScriptTypeAnsible    RemediationScriptType = "ANSIBLE"
	RemediationScriptTypePowershell RemediationScriptType = "POWERSHELL"
)

// ReportViewedPage
type ReportViewedPage string

const (
	ReportViewedPageOrgView                ReportViewedPage = "ORG_VIEW"
	ReportViewedPageAssetOverview          ReportViewedPage = "ASSET_OVERVIEW"
	ReportViewedPageCicdProject            ReportViewedPage = "CICD_PROJECT"
	ReportViewedPageCicdJob                ReportViewedPage = "CICD_JOB"
	ReportViewedPageVulnerabilityDashboard ReportViewedPage = "VULNERABILITY_DASHBOARD"
	ReportViewedPageSecurityDashboard      ReportViewedPage = "SECURITY_DASHBOARD"
)

// ReviewStatus
type ReviewStatus string

const (
	ReviewStatusNotReviewed ReviewStatus = "NOT_REVIEWED"
	ReviewStatusApproved    ReviewStatus = "APPROVED"
	ReviewStatusRejected    ReviewStatus = "REJECTED"
)

// ScoreType
type ScoreType string

const (
	ScoreTypeUnknown    ScoreType = "UNKNOWN"
	ScoreTypeResult     ScoreType = "RESULT"
	ScoreTypeError      ScoreType = "ERROR"
	ScoreTypeUnscored   ScoreType = "UNSCORED"
	ScoreTypeOutOfScope ScoreType = "OUT_OF_SCOPE"
	ScoreTypeDisabled   ScoreType = "DISABLED"
)

// SearchType
type SearchType string

const (
	SearchTypeAggregateScore SearchType = "AGGREGATE_SCORE"
	SearchTypeMvd            SearchType = "MVD"
)

// ServiceAccountOrderField
type ServiceAccountOrderField string

const (
	ServiceAccountOrderFieldID        ServiceAccountOrderField = "ID"
	ServiceAccountOrderFieldName      ServiceAccountOrderField = "NAME"
	ServiceAccountOrderFieldLastUsed  ServiceAccountOrderField = "LAST_USED"
	ServiceAccountOrderFieldCreatedAt ServiceAccountOrderField = "CREATED_AT"
)

// Severity
type Severity string

const (
	SeverityCritical Severity = "CRITICAL"
	SeverityHigh     Severity = "HIGH"
	SeverityMedium   Severity = "MEDIUM"
	SeverityLow      Severity = "LOW"
	SeverityNone     Severity = "NONE"
)

// SpacePlanQueryMutationDestinationType
type SpacePlanQueryMutationDestinationType string

const (
	SpacePlanQueryMutationDestinationTypeActive     SpacePlanQueryMutationDestinationType = "ACTIVE"
	SpacePlanQueryMutationDestinationTypeExceptions SpacePlanQueryMutationDestinationType = "EXCEPTIONS"
	SpacePlanQueryMutationDestinationTypeMilestone  SpacePlanQueryMutationDestinationType = "MILESTONE"
)

// TicketFormat
type TicketFormat string

const (
	TicketFormatJira     TicketFormat = "JIRA"
	TicketFormatMarkdown TicketFormat = "MARKDOWN"
)

// TrustLevel
type TrustLevel string

const (
	TrustLevelAll               TrustLevel = "ALL"
	TrustLevelOfficial          TrustLevel = "OFFICIAL"
	TrustLevelVerifiedPublisher TrustLevel = "VERIFIED_PUBLISHER"
	TrustLevelOss               TrustLevel = "OSS"
	TrustLevelPrivate           TrustLevel = "PRIVATE"
)

// UserState
type UserState string

const (
	UserStateUnknown    UserState = "UNKNOWN"
	UserStateWaitlisted UserState = "WAITLISTED"
	UserStateEnabled    UserState = "ENABLED"
)

// VulnerabilityOrderType
type VulnerabilityOrderType string

const (
	VulnerabilityOrderTypeNewest VulnerabilityOrderType = "NEWEST"
	VulnerabilityOrderTypeSevere VulnerabilityOrderType = "SEVERE"
)
