// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated by gen.go; DO NOT EDIT.

package mondoogql

// APITokenOrderField represents field to order API tokens by.
type APITokenOrderField string

// Field to order API tokens by.
const (
	APITokenOrderFieldName      APITokenOrderField = "NAME"       // Order by name.
	APITokenOrderFieldLastUsed  APITokenOrderField = "LAST_USED"  // Order by last used time.
	APITokenOrderFieldCreatedAt APITokenOrderField = "CREATED_AT" // Order by creation time.
)

// Access represents access level of the object.
type Access string

// Access level of the object.
const (
	AccessAll           Access = "ALL"
	AccessPublic        Access = "PUBLIC"
	AccessAuthenticated Access = "AUTHENTICATED"
	AccessPrivate       Access = "PRIVATE"
)

// ActionType represents action type used when triggering action on client integration.
type ActionType string

// Action type used when triggering action on client integration.
const (
	ActionTypeRetrySetup     ActionType = "RETRY_SETUP"
	ActionTypeRunScan        ActionType = "RUN_SCAN"
	ActionTypeRunExport      ActionType = "RUN_EXPORT"
	ActionTypeRunImport      ActionType = "RUN_IMPORT"
	ActionTypePause          ActionType = "PAUSE"
	ActionTypeUnpause        ActionType = "UNPAUSE"
	ActionTypeMetrics        ActionType = "METRICS"
	ActionTypeUpdate         ActionType = "UPDATE"
	ActionTypeDiagnostics    ActionType = "DIAGNOSTICS"
	ActionTypeClearScanQueue ActionType = "CLEAR_SCAN_QUEUE"
)

// ActivePolicyOrderField represents active policy order field.
type ActivePolicyOrderField string

// Active policy order field.
const (
	ActivePolicyOrderFieldAffectedAssets ActivePolicyOrderField = "AFFECTED_ASSETS"
	ActivePolicyOrderFieldName           ActivePolicyOrderField = "NAME"
)

// AdvisoryPlatformFilter represents possible Advisory filters.
type AdvisoryPlatformFilter string

// possible Advisory filters.
const (
	AdvisoryPlatformFilterRedhat AdvisoryPlatformFilter = "REDHAT"
	AdvisoryPlatformFilterAmazon AdvisoryPlatformFilter = "AMAZON"
	AdvisoryPlatformFilterDebian AdvisoryPlatformFilter = "DEBIAN"
	AdvisoryPlatformFilterUbuntu AdvisoryPlatformFilter = "UBUNTU"
	AdvisoryPlatformFilterAlpine AdvisoryPlatformFilter = "ALPINE"
	AdvisoryPlatformFilterOracle AdvisoryPlatformFilter = "ORACLE"
	AdvisoryPlatformFilterSuse   AdvisoryPlatformFilter = "SUSE"
)

// AgentOrderField represents supported sorting fields for agents.
type AgentOrderField string

// Supported sorting fields for agents.
const (
	AgentOrderFieldId          AgentOrderField = "ID"
	AgentOrderFieldName        AgentOrderField = "NAME"
	AgentOrderFieldPlatform    AgentOrderField = "PLATFORM"
	AgentOrderFieldIp          AgentOrderField = "IP"
	AgentOrderFieldVersion     AgentOrderField = "VERSION"
	AgentOrderFieldStatus      AgentOrderField = "STATUS"
	AgentOrderFieldLastCheckin AgentOrderField = "LAST_CHECKIN"
	AgentOrderFieldHostname    AgentOrderField = "HOSTNAME"
)

// AgentState represents describes agent state.
type AgentState string

// Describes agent state.
const (
	AgentStateActive  AgentState = "ACTIVE"
	AgentStateMissing AgentState = "MISSING"
)

// AggScoresFilterType represents supported filter types for aggScoresSuggestions.
type AggScoresFilterType string

// Supported filter types for aggScoresSuggestions.
const (
	AggScoresFilterTypeState       AggScoresFilterType = "STATE"        // Filter by aggregate score state (Exception Created, Ticket Created, Needs Action).
	AggScoresFilterTypeTypes       AggScoresFilterType = "TYPES"        // Filter by aggregate score types (VULNERABILITY, ADVISORY, ADVISORY, CHECK, POLICY, RISK, ASSET, CONTROL, FRAMEWORK).
	AggScoresFilterTypeRating      AggScoresFilterType = "RATING"       // Filter by rating (CRITICAL, HIGH, MEDIUM, LOW, etc.).
	AggScoresFilterTypePolicyMrn   AggScoresFilterType = "POLICY_MRN"   // Filter by policy MRN.
	AggScoresFilterTypeRiskFactors AggScoresFilterType = "RISK_FACTORS" // Filter by risk factor.
	AggScoresFilterTypePlatform    AggScoresFilterType = "PLATFORM"     // Filter by platform.
)

// AggregateScoreOrderField represents aggregate score order field.
type AggregateScoreOrderField string

// Aggregate score order field.
const (
	AggregateScoreOrderFieldRiskScore       AggregateScoreOrderField = "RISK_SCORE"        // Risk score field.
	AggregateScoreOrderFieldRiskValue       AggregateScoreOrderField = "RISK_VALUE"        // Risk value.
	AggregateScoreOrderFieldRank            AggregateScoreOrderField = "RANK"              // Risk rank.
	AggregateScoreOrderFieldBlastRadius     AggregateScoreOrderField = "BLAST_RADIUS"      // Risk score blast radius.
	AggregateScoreOrderFieldTitle           AggregateScoreOrderField = "TITLE"             // Title.
	AggregateScoreOrderFieldFirstDetectedAt AggregateScoreOrderField = "FIRST_DETECTED_AT" // First detected.
)

// AggregateScoreState represents aggregate score state.
type AggregateScoreState string

// Aggregate score state.
const (
	AggregateScoreStatePreview       AggregateScoreState = "PREVIEW"
	AggregateScoreStateEnabled       AggregateScoreState = "ENABLED"
	AggregateScoreStateSnoozed       AggregateScoreState = "SNOOZED"
	AggregateScoreStateDisabled      AggregateScoreState = "DISABLED"
	AggregateScoreStateFalsePositive AggregateScoreState = "FALSE_POSITIVE"
	AggregateScoreStateWorkaround    AggregateScoreState = "WORKAROUND"
	AggregateScoreStateRiskAccepted  AggregateScoreState = "RISK_ACCEPTED"
)

// AggregateScoreStatus represents status of the agg score.
type AggregateScoreStatus string

// Status of the agg score.
const (
	AggregateScoreStatusExceptionCreated AggregateScoreStatus = "EXCEPTION_CREATED" // Exception is created for the agg score.
	AggregateScoreStatusTicketCreated    AggregateScoreStatus = "TICKET_CREATED"    // Ticket is created for the agg score.
	AggregateScoreStatusNeedsAction      AggregateScoreStatus = "NEEDS_ACTION"      // Agg score needs action.
)

// AggregateScoreType represents aggregate score type field.
type AggregateScoreType string

// Aggregate score type field.
const (
	AggregateScoreTypeVulnerability     AggregateScoreType = "VULNERABILITY"
	AggregateScoreTypeAdvisory          AggregateScoreType = "ADVISORY"
	AggregateScoreTypeCheck             AggregateScoreType = "CHECK"
	AggregateScoreTypePolicy            AggregateScoreType = "POLICY"
	AggregateScoreTypeRisk              AggregateScoreType = "RISK"
	AggregateScoreTypeAsset             AggregateScoreType = "ASSET"
	AggregateScoreTypeControl           AggregateScoreType = "CONTROL"
	AggregateScoreTypeFramework         AggregateScoreType = "FRAMEWORK"
	AggregateScoreTypeSoftware          AggregateScoreType = "SOFTWARE"           // Aggregate score for a software package across all versions currently affected by a vulnerability.
	AggregateScoreTypeVersionedSoftware AggregateScoreType = "VERSIONED_SOFTWARE" // Aggregate score for a software package with a specific version affected by a vulnerability.
	AggregateScoreTypeOther             AggregateScoreType = "OTHER"
)

// AssetFilterType represents supported filter types for asset inventory suggestions.
type AssetFilterType string

// Supported filter types for asset inventory suggestions.
const (
	AssetFilterTypeRiskRating  AssetFilterType = "RISK_RATING" // Filter by risk rating (CRITICAL, HIGH, MEDIUM, LOW, etc.).
	AssetFilterTypePlatform    AssetFilterType = "PLATFORM"    // Filter by platform name (e.g., "ubuntu", "windows", "macos").
	AssetFilterTypeName        AssetFilterType = "NAME"        // Filter by asset name (e.g., "prod-database-1").
	AssetFilterTypeLabels      AssetFilterType = "LABELS"      // Filter by labels (e.g., "owner:sre-team").
	AssetFilterTypeAnnotations AssetFilterType = "ANNOTATIONS" // Filter by annotations (e.g., "mondoo.com/organization: "mondoo-internal").
)

// AssetLinkType represents asset link type.
type AssetLinkType string

// Asset link type.
const (
	AssetLinkTypeFleet AssetLinkType = "FLEET"
	AssetLinkTypeCi    AssetLinkType = "CI"
)

// AssetOrderField represents asset order field.
type AssetOrderField string

// Asset order field.
const (
	AssetOrderFieldId          AssetOrderField = "ID"
	AssetOrderFieldName        AssetOrderField = "NAME"
	AssetOrderFieldPlatform    AssetOrderField = "PLATFORM"
	AssetOrderFieldScore       AssetOrderField = "SCORE"
	AssetOrderFieldLastUpdated AssetOrderField = "LAST_UPDATED"
	AssetOrderFieldRiskScore   AssetOrderField = "RISK_SCORE"
	AssetOrderFieldRiskValue   AssetOrderField = "RISK_VALUE"
)

// AssetOverviewReferenceTypeEnum represents an enumeration of the possible reference types for a item for an asset overview.
type AssetOverviewReferenceTypeEnum string

// An enumeration of the possible reference types for a item for an asset overview.
const (
	AssetOverviewReferenceTypeEnumAsset       AssetOverviewReferenceTypeEnum = "ASSET"
	AssetOverviewReferenceTypeEnumIntegration AssetOverviewReferenceTypeEnum = "INTEGRATION"
)

// AssetReportQueryOrderField represents asset report query order field.
type AssetReportQueryOrderField string

// Asset report query order field.
const (
	AssetReportQueryOrderFieldSeverity AssetReportQueryOrderField = "SEVERITY"
	AssetReportQueryOrderFieldTitle    AssetReportQueryOrderField = "TITLE"
	AssetReportQueryOrderFieldScore    AssetReportQueryOrderField = "SCORE"
)

// AssetSearchOrderField represents asset search order field.
type AssetSearchOrderField string

// Asset search order field.
const (
	AssetSearchOrderFieldId   AssetSearchOrderField = "ID"
	AssetSearchOrderFieldName AssetSearchOrderField = "NAME"
)

// AssetState represents asset state.
type AssetState string

// Asset state.
const (
	AssetStateUnknown    AssetState = "UNKNOWN"
	AssetStateError      AssetState = "ERROR"
	AssetStateDeleted    AssetState = "DELETED"
	AssetStatePending    AssetState = "PENDING"
	AssetStateRunning    AssetState = "RUNNING"
	AssetStateStopping   AssetState = "STOPPING"
	AssetStateStopped    AssetState = "STOPPED"
	AssetStateShutdown   AssetState = "SHUTDOWN"
	AssetStateTerminated AssetState = "TERMINATED"
	AssetStateReboot     AssetState = "REBOOT"
	AssetStateOnline     AssetState = "ONLINE"
	AssetStateOffline    AssetState = "OFFLINE"
)

// AssetSummaryOrderField represents asset summary order field.
type AssetSummaryOrderField string

// Asset summary order field.
const (
	AssetSummaryOrderFieldId        AssetSummaryOrderField = "ID"
	AssetSummaryOrderFieldTitle     AssetSummaryOrderField = "TITLE"
	AssetSummaryOrderFieldPublished AssetSummaryOrderField = "PUBLISHED"
	AssetSummaryOrderFieldModified  AssetSummaryOrderField = "MODIFIED"
	AssetSummaryOrderFieldScore     AssetSummaryOrderField = "SCORE"
)

// AssetUrlStatsCategory represents asset url stats category.
type AssetUrlStatsCategory string

// Asset url stats category.
const (
	AssetUrlStatsCategoryUnscored AssetUrlStatsCategory = "UNSCORED"
	AssetUrlStatsCategoryOk       AssetUrlStatsCategory = "OK"
	AssetUrlStatsCategoryLow      AssetUrlStatsCategory = "LOW"
	AssetUrlStatsCategoryMedium   AssetUrlStatsCategory = "MEDIUM"
	AssetUrlStatsCategoryHigh     AssetUrlStatsCategory = "HIGH"
	AssetUrlStatsCategoryCritical AssetUrlStatsCategory = "CRITICAL"
)

// AssetUrlStatsScope represents asset url stats scope.
type AssetUrlStatsScope string

// Asset url stats scope.
const (
	AssetUrlStatsScopeAll             AssetUrlStatsScope = "ALL"             // Score based on vulnerabilities and security.
	AssetUrlStatsScopeVulnerabilities AssetUrlStatsScope = "VULNERABILITIES" // Score based on vulnerabilities.
	AssetUrlStatsScopeSecurity        AssetUrlStatsScope = "SECURITY"        // Score based on security.
)

// AuditLogFilterType represents supported filter types for audit log suggestions.
type AuditLogFilterType string

// Supported filter types for audit log suggestions.
const (
	AuditLogFilterTypeAction    AuditLogFilterType = "ACTION"    // Filter by action.
	AuditLogFilterTypeTimestamp AuditLogFilterType = "TIMESTAMP" // Filter by time range.
	AuditLogFilterTypeIdentity  AuditLogFilterType = "IDENTITY"  // Filter by identity name.
)

// AuditLogOrderField represents field to order audit log entries by.
type AuditLogOrderField string

// Field to order audit log entries by.
const (
	AuditLogOrderFieldTimestamp AuditLogOrderField = "TIMESTAMP" // Order by timestamp.
)

// AuthBindingOrderField represents field to order WIF auth bindings by.
type AuthBindingOrderField string

// Field to order WIF auth bindings by.
const (
	AuthBindingOrderFieldName       AuthBindingOrderField = "NAME"
	AuthBindingOrderFieldIssuerUri  AuthBindingOrderField = "ISSUER_URI"
	AuthBindingOrderFieldCreateTime AuthBindingOrderField = "CREATE_TIME"
	AuthBindingOrderFieldLastUsed   AuthBindingOrderField = "LAST_USED"
)

// AuthorType represents the type of author.
type AuthorType string

// The type of author.
const (
	AuthorTypeUser           AuthorType = "USER"            // A registered user.
	AuthorTypeServiceAccount AuthorType = "SERVICE_ACCOUNT" // A valid service account.
)

// AzureDevopsTicketContextType represents the type of the ticket context.
type AzureDevopsTicketContextType string

// The type of the ticket context.
const (
	AzureDevopsTicketContextTypeProjects AzureDevopsTicketContextType = "PROJECTS" // The ticket context for Azure Devops projects.
)

// BucketOutputType represents format of the reports for the bucket.
type BucketOutputType string

// Format of the reports for the bucket.
const (
	BucketOutputTypeUnknown BucketOutputType = "UNKNOWN"
	BucketOutputTypeCsv     BucketOutputType = "CSV"
	BucketOutputTypeJsonl   BucketOutputType = "JSONL"
)

// CaseRefStatus represents case reference status.
type CaseRefStatus string

// Case reference status.
const (
	CaseRefStatusOpen   CaseRefStatus = "OPEN"
	CaseRefStatusClosed CaseRefStatus = "CLOSED"
)

// CaseStatus represents case status.
type CaseStatus string

// Case status.
const (
	CaseStatusPending CaseStatus = "PENDING"
	CaseStatusOpen    CaseStatus = "OPEN"
	CaseStatusClosed  CaseStatus = "CLOSED"
	CaseStatusError   CaseStatus = "ERROR"
)

// CasesOrderField represents cases order field.
type CasesOrderField string

// Cases order field.
const (
	CasesOrderFieldSpaceRiskDelta CasesOrderField = "SPACE_RISK_DELTA"
	CasesOrderFieldCreatedAt      CasesOrderField = "CREATED_AT"
)

// CatalogType represents type of the object.
type CatalogType string

// Type of the object.
const (
	CatalogTypeAll       CatalogType = "ALL"
	CatalogTypePolicy    CatalogType = "POLICY"
	CatalogTypeQuerypack CatalogType = "QUERYPACK"
	CatalogTypeQuery     CatalogType = "QUERY"
)

// CheckScoreOrderField represents asset order field.
type CheckScoreOrderField string

// Asset order field.
const (
	CheckScoreOrderFieldAssetName   CheckScoreOrderField = "ASSET_NAME" // ID.
	CheckScoreOrderFieldScore       CheckScoreOrderField = "SCORE"
	CheckScoreOrderFieldRiskValue   CheckScoreOrderField = "RISK_VALUE"
	CheckScoreOrderFieldLastUpdated CheckScoreOrderField = "LAST_UPDATED"
)

// CheckState represents check state.
type CheckState string

// Check state.
const (
	CheckStateActive   CheckState = "ACTIVE"
	CheckStateSnoozed  CheckState = "SNOOZED"
	CheckStateDisabled CheckState = "DISABLED"
)

// ChecksOrderField represents checks order field.
type ChecksOrderField string

// Checks order field.
const (
	ChecksOrderFieldAssetsCount ChecksOrderField = "ASSETS_COUNT"
	ChecksOrderFieldName        ChecksOrderField = "NAME"
	ChecksOrderFieldCompletion  ChecksOrderField = "COMPLETION"
)

// CicdProjectOrderField represents input for ordering CI/CD projects.
type CicdProjectOrderField string

// Input for ordering CI/CD projects.
const (
	CicdProjectOrderFieldName CicdProjectOrderField = "NAME"
)

// ClientIntegrationType represents type of the client integration.
type ClientIntegrationType string

// Type of the client integration.
const (
	ClientIntegrationTypeUnknown                 ClientIntegrationType = "UNKNOWN"
	ClientIntegrationTypeK8s                     ClientIntegrationType = "K8S"
	ClientIntegrationTypeAws                     ClientIntegrationType = "AWS"
	ClientIntegrationTypeManagedClient           ClientIntegrationType = "MANAGED_CLIENT"
	ClientIntegrationTypeAzure                   ClientIntegrationType = "AZURE"
	ClientIntegrationTypeMs365                   ClientIntegrationType = "MS365"
	ClientIntegrationTypeGcp                     ClientIntegrationType = "GCP"
	ClientIntegrationTypeGoogleWorkspace         ClientIntegrationType = "GOOGLE_WORKSPACE"
	ClientIntegrationTypeOkta                    ClientIntegrationType = "OKTA"
	ClientIntegrationTypeBigquery                ClientIntegrationType = "BIGQUERY"
	ClientIntegrationTypeSnowflake               ClientIntegrationType = "SNOWFLAKE"
	ClientIntegrationTypeAwsS3                   ClientIntegrationType = "AWS_S3"
	ClientIntegrationTypeS3                      ClientIntegrationType = "S3"
	ClientIntegrationTypeHostedSlack             ClientIntegrationType = "HOSTED_SLACK"
	ClientIntegrationTypeGithub                  ClientIntegrationType = "GITHUB"
	ClientIntegrationTypeGitlab                  ClientIntegrationType = "GITLAB"
	ClientIntegrationTypeGcsBucket               ClientIntegrationType = "GCS_BUCKET"
	ClientIntegrationTypePostgres                ClientIntegrationType = "POSTGRES"
	ClientIntegrationTypeOci                     ClientIntegrationType = "OCI"
	ClientIntegrationTypeTicketSystemJira        ClientIntegrationType = "TICKET_SYSTEM_JIRA"
	ClientIntegrationTypeAwsHosted               ClientIntegrationType = "AWS_HOSTED"
	ClientIntegrationTypeAzureBlob               ClientIntegrationType = "AZURE_BLOB"
	ClientIntegrationTypeHost                    ClientIntegrationType = "HOST"
	ClientIntegrationTypeTicketSystemEmail       ClientIntegrationType = "TICKET_SYSTEM_EMAIL"
	ClientIntegrationTypeTicketSystemZendesk     ClientIntegrationType = "TICKET_SYSTEM_ZENDESK"
	ClientIntegrationTypeMicrosoftDefender       ClientIntegrationType = "MICROSOFT_DEFENDER"
	ClientIntegrationTypeTicketSystemGithub      ClientIntegrationType = "TICKET_SYSTEM_GITHUB"
	ClientIntegrationTypeTicketSystemGitlab      ClientIntegrationType = "TICKET_SYSTEM_GITLAB"
	ClientIntegrationTypeShodan                  ClientIntegrationType = "SHODAN"
	ClientIntegrationTypeTicketSystemAzureDevops ClientIntegrationType = "TICKET_SYSTEM_AZURE_DEVOPS"
	ClientIntegrationTypeSentinelOne             ClientIntegrationType = "SENTINEL_ONE"
	ClientIntegrationTypeCrowdstrikeFalcon       ClientIntegrationType = "CROWDSTRIKE_FALCON"
	ClientIntegrationTypeSecurityPipelineGithub  ClientIntegrationType = "SECURITY_PIPELINE_GITHUB"
	ClientIntegrationTypeTicketSystemWebhook     ClientIntegrationType = "TICKET_SYSTEM_WEBHOOK"
)

// ComparisonOperator represents comparison operators for filtering.
type ComparisonOperator string

// Comparison operators for filtering.
const (
	ComparisonOperatorGt ComparisonOperator = "GT" // Greater than.
	ComparisonOperatorLt ComparisonOperator = "LT" // Less than.
)

// ComplianceAssetOrderField represents compliance asset order field.
type ComplianceAssetOrderField string

// Compliance asset order field.
const (
	ComplianceAssetOrderFieldId          ComplianceAssetOrderField = "ID"
	ComplianceAssetOrderFieldName        ComplianceAssetOrderField = "NAME"
	ComplianceAssetOrderFieldPlatform    ComplianceAssetOrderField = "PLATFORM"
	ComplianceAssetOrderFieldCompletion  ComplianceAssetOrderField = "COMPLETION"
	ComplianceAssetOrderFieldLastUpdated ComplianceAssetOrderField = "LAST_UPDATED"
)

// ComplianceFrameworkMutationAction represents compliance framework mutation action.
type ComplianceFrameworkMutationAction string

// Compliance framework mutation action.
const (
	ComplianceFrameworkMutationActionEnable  ComplianceFrameworkMutationAction = "ENABLE"
	ComplianceFrameworkMutationActionPreview ComplianceFrameworkMutationAction = "PREVIEW"
	ComplianceFrameworkMutationActionDisable ComplianceFrameworkMutationAction = "DISABLE"
)

// ComplianceFrameworkState represents compliance framework state.
type ComplianceFrameworkState string

// Compliance framework state.
const (
	ComplianceFrameworkStateActive   ComplianceFrameworkState = "ACTIVE"
	ComplianceFrameworkStatePreview  ComplianceFrameworkState = "PREVIEW"
	ComplianceFrameworkStateDisabled ComplianceFrameworkState = "DISABLED"
)

// ContentSearchResultItemOrderField represents order fields for content search results.
type ContentSearchResultItemOrderField string

// Order fields for content search results.
const (
	ContentSearchResultItemOrderFieldName ContentSearchResultItemOrderField = "NAME"
)

// ControlScoreOrderField represents control Score order field.
type ControlScoreOrderField string

// Control Score order field.
const (
	ControlScoreOrderFieldAssetName   ControlScoreOrderField = "ASSET_NAME" // ID.
	ControlScoreOrderFieldScore       ControlScoreOrderField = "SCORE"
	ControlScoreOrderFieldLastUpdated ControlScoreOrderField = "LAST_UPDATED"
)

// ControlState represents control state.
type ControlState string

// Control state.
const (
	ControlStateActive        ControlState = "ACTIVE"
	ControlStateSnoozed       ControlState = "SNOOZED"
	ControlStateDisabled      ControlState = "DISABLED"
	ControlStateOutOfScope    ControlState = "OUT_OF_SCOPE"
	ControlStateRiskAccepted  ControlState = "RISK_ACCEPTED"
	ControlStateFalsePositive ControlState = "FALSE_POSITIVE"
	ControlStateWorkaround    ControlState = "WORKAROUND"
)

// ControlsOrderField represents controls order field.
type ControlsOrderField string

// Controls order field.
const (
	ControlsOrderFieldId         ControlsOrderField = "ID"
	ControlsOrderFieldTitle      ControlsOrderField = "TITLE"
	ControlsOrderFieldCompletion ControlsOrderField = "COMPLETION"
	ControlsOrderFieldChecks     ControlsOrderField = "CHECKS"
	ControlsOrderFieldAssets     ControlsOrderField = "ASSETS"
	ControlsOrderFieldExceptions ControlsOrderField = "EXCEPTIONS"
	ControlsOrderFieldQueries    ControlsOrderField = "QUERIES"
)

// CveState represents possible CVE states.
type CveState string

// Possible CVE states.
const (
	CveStateInvalid    CveState = "INVALID"
	CveStatePublic     CveState = "PUBLIC"
	CveStateReserved   CveState = "RESERVED"
	CveStateReplacedBy CveState = "REPLACED_BY"
	CveStateSplitFrom  CveState = "SPLIT_FROM"
	CveStateMergedTo   CveState = "MERGED_TO"
)

// DataQueryOrderField represents data query order field.
type DataQueryOrderField string

// Data query order field.
const (
	DataQueryOrderFieldAssetName   DataQueryOrderField = "ASSET_NAME"
	DataQueryOrderFieldLastUpdated DataQueryOrderField = "LAST_UPDATED"
)

// DocumentFormat represents document format.
type DocumentFormat string

// Document format.
const (
	DocumentFormatPdf   DocumentFormat = "PDF"
	DocumentFormatCsv   DocumentFormat = "CSV"
	DocumentFormatJsonl DocumentFormat = "JSONL"
)

// DocumentStatus represents document status.
type DocumentStatus string

// Document status.
const (
	DocumentStatusQueued    DocumentStatus = "QUEUED"
	DocumentStatusRunning   DocumentStatus = "RUNNING"
	DocumentStatusCompleted DocumentStatus = "COMPLETED"
	DocumentStatusFailed    DocumentStatus = "FAILED"
)

// DocumentType represents document type.
type DocumentType string

// Document type.
const (
	DocumentTypeFrameworkReport       DocumentType = "FRAMEWORK_REPORT"
	DocumentTypeControlReport         DocumentType = "CONTROL_REPORT"
	DocumentTypeExport                DocumentType = "EXPORT"
	DocumentTypeAssetReport           DocumentType = "ASSET_REPORT"
	DocumentTypeAdvisoryReport        DocumentType = "ADVISORY_REPORT"
	DocumentTypeVulnerabilityReport   DocumentType = "VULNERABILITY_REPORT"
	DocumentTypeCheckReport           DocumentType = "CHECK_REPORT"
	DocumentTypeSecurityReport        DocumentType = "SECURITY_REPORT"
	DocumentTypeChecksReport          DocumentType = "CHECKS_REPORT"
	DocumentTypeVulnerabilitiesReport DocumentType = "VULNERABILITIES_REPORT"
)

// EOLStatus represents end-of-life status.
type EOLStatus string

// End-of-life status.
const (
	EOLStatusScheduled EOLStatus = "SCHEDULED"
	EOLStatusEol       EOLStatus = "EOL"
)

// EmailPreferenceList represents email preference list.
type EmailPreferenceList string

// Email preference list.
const (
	EmailPreferenceListNewsletterGeneral                   EmailPreferenceList = "NEWSLETTER_GENERAL"
	EmailPreferenceListNewsletterProduct                   EmailPreferenceList = "NEWSLETTER_PRODUCT"
	EmailPreferenceListNewsletterEvents                    EmailPreferenceList = "NEWSLETTER_EVENTS"
	EmailPreferenceListNotificationWeeklyReports           EmailPreferenceList = "NOTIFICATION_WEEKLY_REPORTS"
	EmailPreferenceListNotificationSpaceAlerts             EmailPreferenceList = "NOTIFICATION_SPACE_ALERTS"
	EmailPreferenceListNotificationExpiringExceptions      EmailPreferenceList = "NOTIFICATION_EXPIRING_EXCEPTIONS"
	EmailPreferenceListNotificationExceptionsPendingReview EmailPreferenceList = "NOTIFICATION_EXCEPTIONS_PENDING_REVIEW"
)

// ExceptionFilterType represents exception filter type.
type ExceptionFilterType string

// Exception filter type.
const (
	ExceptionFilterTypeStatus        ExceptionFilterType = "STATUS"         // Filter by exception status (NOT_REVIEWED, APPROVED, REJECTED, etc.).
	ExceptionFilterTypeCreatedBy     ExceptionFilterType = "CREATED_BY"     // Filter by who created the exception.
	ExceptionFilterTypeApprovedBy    ExceptionFilterType = "APPROVED_BY"    // Filter by who approved the exception.
	ExceptionFilterTypeExceptionType ExceptionFilterType = "EXCEPTION_TYPE" // Filter by exception type (CVE, ADVISORY, SECURITY, COMPLIANCE).
	ExceptionFilterTypeExpiring      ExceptionFilterType = "EXPIRING"       // Filter by expiration status (EXPIRING, NOT_EXPIRING).
)

// ExceptionGroupExtensionStatus represents the review status for an exception group extension.
type ExceptionGroupExtensionStatus string

// The review status for an exception group extension.
const (
	ExceptionGroupExtensionStatusNotReviewed ExceptionGroupExtensionStatus = "NOT_REVIEWED"
	ExceptionGroupExtensionStatusApproved    ExceptionGroupExtensionStatus = "APPROVED"
	ExceptionGroupExtensionStatusRejected    ExceptionGroupExtensionStatus = "REJECTED"
)

// ExceptionMutationAction represents the action to apply to the exception.
type ExceptionMutationAction string

// The action to apply to the exception.
const (
	ExceptionMutationActionEnable        ExceptionMutationAction = "ENABLE"
	ExceptionMutationActionDisable       ExceptionMutationAction = "DISABLE"
	ExceptionMutationActionSnooze        ExceptionMutationAction = "SNOOZE"
	ExceptionMutationActionRiskAccepted  ExceptionMutationAction = "RISK_ACCEPTED"
	ExceptionMutationActionFalsePositive ExceptionMutationAction = "FALSE_POSITIVE"
	ExceptionMutationActionWorkaround    ExceptionMutationAction = "WORKAROUND"
	ExceptionMutationActionOutOfScope    ExceptionMutationAction = "OUT_OF_SCOPE" // Applicable only for compliance.
)

// ExceptionReviewAction represents the type of review action.
type ExceptionReviewAction string

// The type of review action.
const (
	ExceptionReviewActionApproved ExceptionReviewAction = "APPROVED"
	ExceptionReviewActionRejected ExceptionReviewAction = "REJECTED"
)

// ExceptionType represents the type of the exception.
type ExceptionType string

// The type of the exception.
const (
	ExceptionTypeCompliance ExceptionType = "COMPLIANCE"
	ExceptionTypeSecurity   ExceptionType = "SECURITY"
	ExceptionTypeCve        ExceptionType = "CVE"
	ExceptionTypeAdvisory   ExceptionType = "ADVISORY"
)

// FindingFilterType represents finding filter type.
type FindingFilterType string

// Finding filter type.
const (
	FindingFilterTypeState       FindingFilterType = "STATE"        // State filter.
	FindingFilterTypeTypes       FindingFilterType = "TYPES"        // Filter by finding types (CHECK, CVE, ADVISORY, PACKAGE, etc.).
	FindingFilterTypeRating      FindingFilterType = "RATING"       // Filter by rating (CRITICAL, HIGH, MEDIUM, LOW, etc.).
	FindingFilterTypePolicyMrn   FindingFilterType = "POLICY_MRN"   // Filter by policy MRN.
	FindingFilterTypeSoftwareMrn FindingFilterType = "SOFTWARE_MRN" // Filter vulnerabilities by software MRN.
	FindingFilterTypeRiskFactors FindingFilterType = "RISK_FACTORS" // Filter by risk factor.
)

// FindingType represents finding type.
type FindingType string

// Finding type.
const (
	FindingTypeCheck      FindingType = "CHECK"
	FindingTypeCve        FindingType = "CVE"
	FindingTypeAdvisory   FindingType = "ADVISORY"
	FindingTypePackage    FindingType = "PACKAGE"
	FindingTypeOsPackage  FindingType = "OS_PACKAGE"
	FindingTypeAppPackage FindingType = "APP_PACKAGE"
)

// FindingsOrderField represents findings order field.
type FindingsOrderField string

// Findings order field.
const (
	FindingsOrderFieldAssetName   FindingsOrderField = "ASSET_NAME" // ID.
	FindingsOrderFieldBaseScore   FindingsOrderField = "BASE_SCORE"
	FindingsOrderFieldRiskScore   FindingsOrderField = "RISK_SCORE"
	FindingsOrderFieldRiskValue   FindingsOrderField = "RISK_VALUE"
	FindingsOrderFieldLastUpdated FindingsOrderField = "LAST_UPDATED"
	FindingsOrderFieldPackageName FindingsOrderField = "PACKAGE_NAME"
	FindingsOrderFieldRiskFactors FindingsOrderField = "RISK_FACTORS"
	FindingsOrderFieldFirstFound  FindingsOrderField = "FIRST_FOUND"
	FindingsOrderFieldMrn         FindingsOrderField = "MRN"
	FindingsOrderFieldCvssScore   FindingsOrderField = "CVSS_SCORE"
)

// FormatType represents output format.
type FormatType string

// Output format.
const (
	FormatTypeJson FormatType = "JSON"
	FormatTypeCsv  FormatType = "CSV"
)

// GitPipelineKind represents enum representing the different types of Git pipelines.
type GitPipelineKind string

// Enum representing the different types of Git pipelines.
const (
	GitPipelineKindPullRequest GitPipelineKind = "PULL_REQUEST"
	GitPipelineKindBranch      GitPipelineKind = "BRANCH"
	GitPipelineKindTag         GitPipelineKind = "TAG"
	GitPipelineKindUnknown     GitPipelineKind = "UNKNOWN"
)

// GithubIntegrationType represents github integration type.
type GithubIntegrationType string

// Github integration type.
const (
	GithubIntegrationTypeRepo GithubIntegrationType = "REPO"
	GithubIntegrationTypeOrg  GithubIntegrationType = "ORG"
)

// GitlabIntegrationType represents gitlab integration type.
type GitlabIntegrationType string

// Gitlab integration type.
const (
	GitlabIntegrationTypeGroup GitlabIntegrationType = "GROUP" // denotes a limiting group for the integration, we do not want to discover groups not related to this group.
	GitlabIntegrationTypeNone  GitlabIntegrationType = "NONE"  // nothing is limited, discover all groups.
)

// Grade represents deprecated, use Score.grade instead.
type Grade string

// deprecated, use Score.grade instead.
const (
	GradeA Grade = "A"
	GradeB Grade = "B"
	GradeC Grade = "C"
	GradeD Grade = "D"
	GradeF Grade = "F"
	GradeU Grade = "U"
)

// ICON_IDS represents eNUM for icon ids.
type ICON_IDS string

// ENUM for icon ids.
const (
	ICON_IDSAdobe                     ICON_IDS = "ADOBE"
	ICON_IDSAdobeIllustrator          ICON_IDS = "ADOBE_ILLUSTRATOR"
	ICON_IDSAdobeIndesign             ICON_IDS = "ADOBE_INDESIGN"
	ICON_IDSAdobePhotoshop            ICON_IDS = "ADOBE_PHOTOSHOP"
	ICON_IDSAix                       ICON_IDS = "AIX"
	ICON_IDSAlmaLinux                 ICON_IDS = "ALMA_LINUX"
	ICON_IDSAlpine                    ICON_IDS = "ALPINE"
	ICON_IDSAmazon                    ICON_IDS = "AMAZON"
	ICON_IDSApple                     ICON_IDS = "APPLE"
	ICON_IDSArch                      ICON_IDS = "ARCH"
	ICON_IDSArista                    ICON_IDS = "ARISTA"
	ICON_IDSAsset                     ICON_IDS = "ASSET"
	ICON_IDSAtlassian                 ICON_IDS = "ATLASSIAN"
	ICON_IDSAws                       ICON_IDS = "AWS"
	ICON_IDSAzure                     ICON_IDS = "AZURE"
	ICON_IDSBusybox                   ICON_IDS = "BUSYBOX"
	ICON_IDSCentos                    ICON_IDS = "CENTOS"
	ICON_IDSCheck                     ICON_IDS = "CHECK"
	ICON_IDSCisaKev                   ICON_IDS = "CISA_KEV"
	ICON_IDSContainers                ICON_IDS = "CONTAINERS"
	ICON_IDSCve                       ICON_IDS = "CVE"
	ICON_IDSDebian                    ICON_IDS = "DEBIAN"
	ICON_IDSDefault                   ICON_IDS = "DEFAULT"
	ICON_IDSDns                       ICON_IDS = "DNS"
	ICON_IDSDockerDesktop             ICON_IDS = "DOCKER_DESKTOP"
	ICON_IDSDomainsAndHosts           ICON_IDS = "DOMAINS_AND_HOSTS"
	ICON_IDSEquinix                   ICON_IDS = "EQUINIX"
	ICON_IDSEuroLinux                 ICON_IDS = "EURO_LINUX"
	ICON_IDSFedora                    ICON_IDS = "FEDORA"
	ICON_IDSGcp                       ICON_IDS = "GCP"
	ICON_IDSGentoo                    ICON_IDS = "GENTOO"
	ICON_IDSGithub                    ICON_IDS = "GITHUB"
	ICON_IDSGitlab                    ICON_IDS = "GITLAB"
	ICON_IDSGoogleChrome              ICON_IDS = "GOOGLE_CHROME"
	ICON_IDSGoogleWorkspace           ICON_IDS = "GOOGLE_WORKSPACE"
	ICON_IDSIac                       ICON_IDS = "IAC"
	ICON_IDSIpmi                      ICON_IDS = "IPMI"
	ICON_IDSK8s                       ICON_IDS = "K8S"
	ICON_IDSKali                      ICON_IDS = "KALI"
	ICON_IDSLinux                     ICON_IDS = "LINUX"
	ICON_IDSLinuxMint                 ICON_IDS = "LINUX_MINT"
	ICON_IDSMacos                     ICON_IDS = "MACOS"
	ICON_IDSManjaro                   ICON_IDS = "MANJARO"
	ICON_IDSMetasploit                ICON_IDS = "METASPLOIT"
	ICON_IDSMicrosoft                 ICON_IDS = "MICROSOFT"
	ICON_IDSMicrosoftDotnet           ICON_IDS = "MICROSOFT_DOTNET"
	ICON_IDSMicrosoftEdge             ICON_IDS = "MICROSOFT_EDGE"
	ICON_IDSMicrosoftExcel            ICON_IDS = "MICROSOFT_EXCEL"
	ICON_IDSMicrosoftPowerpoint       ICON_IDS = "MICROSOFT_POWERPOINT"
	ICON_IDSMicrosoftTeams            ICON_IDS = "MICROSOFT_TEAMS"
	ICON_IDSMicrosoftVisualStudioCode ICON_IDS = "MICROSOFT_VISUAL_STUDIO_CODE"
	ICON_IDSMicrosoftWord             ICON_IDS = "MICROSOFT_WORD"
	ICON_IDSMondoo                    ICON_IDS = "MONDOO"
	ICON_IDSMozilla                   ICON_IDS = "MOZILLA"
	ICON_IDSMozillaFirefox            ICON_IDS = "MOZILLA_FIREFOX"
	ICON_IDSMs365                     ICON_IDS = "MS365"
	ICON_IDSNetworkDevices            ICON_IDS = "NETWORK_DEVICES"
	ICON_IDSNistNvd                   ICON_IDS = "NIST_NVD"
	ICON_IDSNmap                      ICON_IDS = "NMAP"
	ICON_IDSNotepadPlusPlus           ICON_IDS = "NOTEPAD_PLUS_PLUS"
	ICON_IDSOci                       ICON_IDS = "OCI"
	ICON_IDSOkta                      ICON_IDS = "OKTA"
	ICON_IDSOpcua                     ICON_IDS = "OPCUA"
	ICON_IDSOpenwrt                   ICON_IDS = "OPENWRT"
	ICON_IDSOperatingSystem           ICON_IDS = "OPERATING_SYSTEM"
	ICON_IDSOracle                    ICON_IDS = "ORACLE"
	ICON_IDSOther                     ICON_IDS = "OTHER"
	ICON_IDSPolicy                    ICON_IDS = "POLICY"
	ICON_IDSPop                       ICON_IDS = "POP"
	ICON_IDSPython                    ICON_IDS = "PYTHON"
	ICON_IDSRaspbian                  ICON_IDS = "RASPBIAN"
	ICON_IDSRedhat                    ICON_IDS = "REDHAT"
	ICON_IDSRisk                      ICON_IDS = "RISK"
	ICON_IDSRockyLinux                ICON_IDS = "ROCKY_LINUX"
	ICON_IDSSafari                    ICON_IDS = "SAFARI"
	ICON_IDSScientificLinux           ICON_IDS = "SCIENTIFIC_LINUX"
	ICON_IDSSevenZip                  ICON_IDS = "SEVEN_ZIP"
	ICON_IDSSlack                     ICON_IDS = "SLACK"
	ICON_IDSSuse                      ICON_IDS = "SUSE"
	ICON_IDSTailscale                 ICON_IDS = "TAILSCALE"
	ICON_IDSTerraform                 ICON_IDS = "TERRAFORM"
	ICON_IDSUbuntu                    ICON_IDS = "UBUNTU"
	ICON_IDSVcd                       ICON_IDS = "VCD"
	ICON_IDSVlcMediaPlayer            ICON_IDS = "VLC_MEDIA_PLAYER"
	ICON_IDSVmware                    ICON_IDS = "VMWARE"
	ICON_IDSVmwareFusion              ICON_IDS = "VMWARE_FUSION"
	ICON_IDSVmwarePhoton              ICON_IDS = "VMWARE_PHOTON"
	ICON_IDSVmwareTools               ICON_IDS = "VMWARE_TOOLS"
	ICON_IDSWebex                     ICON_IDS = "WEBEX"
	ICON_IDSWindows                   ICON_IDS = "WINDOWS"
	ICON_IDSWindows10                 ICON_IDS = "WINDOWS_10"
	ICON_IDSWindows11                 ICON_IDS = "WINDOWS_11"
	ICON_IDSWireshark                 ICON_IDS = "WIRESHARK"
	ICON_IDSWrLinux                   ICON_IDS = "WR_LINUX"
)

// IntegrationMessageStatus represents integrationMessageStatus denotes the status of the message reported by the integration.
type IntegrationMessageStatus string

// IntegrationMessageStatus denotes the status of the message reported by the integration.
const (
	IntegrationMessageStatusInfo    IntegrationMessageStatus = "INFO"
	IntegrationMessageStatusWarning IntegrationMessageStatus = "WARNING"
	IntegrationMessageStatusError   IntegrationMessageStatus = "ERROR"
)

// IntegrationType represents summary of client integrations.
type IntegrationType string

// Summary of client integrations.
const (
	IntegrationTypeUnknown                 IntegrationType = "UNKNOWN"
	IntegrationTypeManagedClient           IntegrationType = "MANAGED_CLIENT"
	IntegrationTypeK8s                     IntegrationType = "K8S"
	IntegrationTypeAws                     IntegrationType = "AWS"
	IntegrationTypeAzure                   IntegrationType = "AZURE"
	IntegrationTypeMs365                   IntegrationType = "MS365"
	IntegrationTypeSlack                   IntegrationType = "SLACK"
	IntegrationTypeMsteams                 IntegrationType = "MSTEAMS"
	IntegrationTypeTelegram                IntegrationType = "TELEGRAM"
	IntegrationTypeHttppost                IntegrationType = "HTTPPOST"
	IntegrationTypeGcp                     IntegrationType = "GCP"
	IntegrationTypeGoogleWorkspace         IntegrationType = "GOOGLE_WORKSPACE"
	IntegrationTypeOkta                    IntegrationType = "OKTA"
	IntegrationTypeBigquery                IntegrationType = "BIGQUERY"
	IntegrationTypeSnowflake               IntegrationType = "SNOWFLAKE"
	IntegrationTypeAwsS3                   IntegrationType = "AWS_S3"
	IntegrationTypeS3                      IntegrationType = "S3"
	IntegrationTypeHostedSlack             IntegrationType = "HOSTED_SLACK"
	IntegrationTypeGithub                  IntegrationType = "GITHUB"
	IntegrationTypeGitlab                  IntegrationType = "GITLAB"
	IntegrationTypeGcsBucket               IntegrationType = "GCS_BUCKET"
	IntegrationTypePostgres                IntegrationType = "POSTGRES"
	IntegrationTypeOci                     IntegrationType = "OCI"
	IntegrationTypeTicketSystemJira        IntegrationType = "TICKET_SYSTEM_JIRA"
	IntegrationTypeAzureBlob               IntegrationType = "AZURE_BLOB"
	IntegrationTypeHost                    IntegrationType = "HOST"
	IntegrationTypeAwsHosted               IntegrationType = "AWS_HOSTED"
	IntegrationTypeTicketSystemEmail       IntegrationType = "TICKET_SYSTEM_EMAIL"
	IntegrationTypeTicketSystemZendesk     IntegrationType = "TICKET_SYSTEM_ZENDESK"
	IntegrationTypeMicrosoftDefender       IntegrationType = "MICROSOFT_DEFENDER"
	IntegrationTypeTicketSystemGithub      IntegrationType = "TICKET_SYSTEM_GITHUB"
	IntegrationTypeTicketSystemGitlab      IntegrationType = "TICKET_SYSTEM_GITLAB"
	IntegrationTypeShodan                  IntegrationType = "SHODAN"
	IntegrationTypeTicketSystemAzureDevops IntegrationType = "TICKET_SYSTEM_AZURE_DEVOPS"
	IntegrationTypeSentinelOne             IntegrationType = "SENTINEL_ONE"
	IntegrationTypeCrowdstrikeFalcon       IntegrationType = "CROWDSTRIKE_FALCON"
	IntegrationTypeSecurityPipelineGithub  IntegrationType = "SECURITY_PIPELINE_GITHUB"
	IntegrationTypeTicketSystemWebhook     IntegrationType = "TICKET_SYSTEM_WEBHOOK"
)

// InvitationOrderField represents field to order invitations by.
type InvitationOrderField string

// Field to order invitations by.
const (
	InvitationOrderFieldCreated InvitationOrderField = "CREATED"
)

// InvitationState represents state of an invitation.
type InvitationState string

// State of an invitation.
const (
	InvitationStatePending  InvitationState = "PENDING"
	InvitationStateAccepted InvitationState = "ACCEPTED"
	InvitationStateDeclined InvitationState = "DECLINED"
	InvitationStateCanceled InvitationState = "CANCELED"
)

// JiraTicketContextType represents the type of the ticket context.
type JiraTicketContextType string

// The type of the ticket context.
const (
	JiraTicketContextTypeProjects JiraTicketContextType = "PROJECTS" // The ticket context for Jira projects.
	JiraTicketContextTypeUsers    JiraTicketContextType = "USERS"    // The ticket context for Jira users.
)

// K8sScanNodesStyle represents k8s node scanning style.
type K8sScanNodesStyle string

// K8s node scanning style.
const (
	K8sScanNodesStyleUnknown    K8sScanNodesStyle = "UNKNOWN"
	K8sScanNodesStyleCronjob    K8sScanNodesStyle = "CRONJOB"
	K8sScanNodesStyleDeployment K8sScanNodesStyle = "DEPLOYMENT"
	K8sScanNodesStyleDaemonset  K8sScanNodesStyle = "DAEMONSET"
)

// ListExceptionGroupsOrderField represents exception groups order field.
type ListExceptionGroupsOrderField string

// Exception groups order field.
const (
	ListExceptionGroupsOrderFieldCreatedAt  ListExceptionGroupsOrderField = "CREATED_AT"
	ListExceptionGroupsOrderFieldValidUntil ListExceptionGroupsOrderField = "VALID_UNTIL"
)

// ListFrameworksFilterState represents list frameworks filter state.
type ListFrameworksFilterState string

// List frameworks filter state.
const (
	ListFrameworksFilterStateActive    ListFrameworksFilterState = "ACTIVE"
	ListFrameworksFilterStateAvailable ListFrameworksFilterState = "AVAILABLE"
)

// MembershipOrderField represents field to order memberships by.
type MembershipOrderField string

// Field to order memberships by.
const (
	MembershipOrderFieldName MembershipOrderField = "NAME"
)

// MqueryAssetDataFormat represents mquery asset data format.
type MqueryAssetDataFormat string

// Mquery asset data format.
const (
	MqueryAssetDataFormatJson MqueryAssetDataFormat = "JSON"
)

// MqueryState represents mquery state.
type MqueryState string

// Mquery state.
const (
	MqueryStateEnabled  MqueryState = "ENABLED"
	MqueryStateDisabled MqueryState = "DISABLED"
	MqueryStateIgnored  MqueryState = "IGNORED"
	MqueryStateSnoozed  MqueryState = "SNOOZED"
)

// MqueryType represents mquery type.
type MqueryType string

// Mquery type.
const (
	MqueryTypeData    MqueryType = "DATA"
	MqueryTypeScoring MqueryType = "SCORING"
)

// MvdEcosystem represents mVD ecosystem.
type MvdEcosystem string

// MVD ecosystem.
const (
	MvdEcosystemAlmalinux   MvdEcosystem = "ALMALINUX"
	MvdEcosystemAlpine      MvdEcosystem = "ALPINE"
	MvdEcosystemDebian      MvdEcosystem = "DEBIAN"
	MvdEcosystemFedora      MvdEcosystem = "FEDORA"
	MvdEcosystemLinux       MvdEcosystem = "LINUX"
	MvdEcosystemMacos       MvdEcosystem = "MACOS"
	MvdEcosystemOpensuse    MvdEcosystem = "OPENSUSE"
	MvdEcosystemPhotonos    MvdEcosystem = "PHOTONOS"
	MvdEcosystemRedhat      MvdEcosystem = "REDHAT"
	MvdEcosystemRockylinux  MvdEcosystem = "ROCKYLINUX"
	MvdEcosystemSuse        MvdEcosystem = "SUSE"
	MvdEcosystemUbuntu      MvdEcosystem = "UBUNTU"
	MvdEcosystemWindows     MvdEcosystem = "WINDOWS"
	MvdEcosystemWindowsappx MvdEcosystem = "WINDOWSAPPX"
)

// NotificationType represents slack notification type enum.
type NotificationType string

// Slack notification type enum.
const (
	NotificationTypeTriageConversations NotificationType = "TRIAGE_CONVERSATIONS" // Send triage conversations for findings.
	NotificationTypeAssetUpdates        NotificationType = "ASSET_UPDATES"        // Send asset update notfication streams.
)

// OrderDirection represents defines the possible directions in which to sort a list of items.
type OrderDirection string

// Defines the possible directions in which to sort a list of items.
const (
	OrderDirectionAsc  OrderDirection = "ASC"  // Ascending order. For example, from A to Z or from lowest to highest.
	OrderDirectionDesc OrderDirection = "DESC" // Descending order. For example, from Z to A or from highest to lowest.
)

// PackageManager represents remediation script type.
type PackageManager string

// Remediation script type.
const (
	PackageManagerDpkg       PackageManager = "DPKG"       // DPKG.
	PackageManagerYum        PackageManager = "YUM"        // YUM.
	PackageManagerDnf        PackageManager = "DNF"        // DNF.
	PackageManagerZypper     PackageManager = "ZYPPER"     // ZYPPER.
	PackageManagerPowershell PackageManager = "POWERSHELL" // POWERSHELL.
	PackageManagerAix        PackageManager = "AIX"        // AIX.
	PackageManagerBrew       PackageManager = "BREW"       // BREW aka. HOMEBREW.
)

// PackageScoresOrderField represents packageScores order fields.
type PackageScoresOrderField string

// PackageScores order fields.
const (
	PackageScoresOrderFieldScore       PackageScoresOrderField = "SCORE"
	PackageScoresOrderFieldAssetName   PackageScoresOrderField = "ASSET_NAME"
	PackageScoresOrderFieldLastUpdated PackageScoresOrderField = "LAST_UPDATED"
	PackageScoresOrderFieldRiskFactors PackageScoresOrderField = "RISK_FACTORS"
	PackageScoresOrderFieldFirstFound  PackageScoresOrderField = "FIRST_FOUND"
	PackageScoresOrderFieldPackageName PackageScoresOrderField = "PACKAGE_NAME"
	PackageScoresOrderFieldRiskScore   PackageScoresOrderField = "RISK_SCORE"
)

// PackageType represents possible package types.
type PackageType string

// possible package types.
const (
	PackageTypeOsPackage   PackageType = "OS_PACKAGE"
	PackageTypeApplication PackageType = "APPLICATION"
)

// PackagesOrderField represents possible package order fields.
type PackagesOrderField string

// possible package order fields.
const (
	PackagesOrderFieldName        PackagesOrderField = "NAME"
	PackagesOrderFieldScore       PackagesOrderField = "SCORE"
	PackagesOrderFieldFirstFound  PackagesOrderField = "FIRST_FOUND"
	PackagesOrderFieldRiskFactors PackagesOrderField = "RISK_FACTORS"
)

// PlatformKind represents platform kind.
type PlatformKind string

// Platform kind.
const (
	PlatformKindUnknown             PlatformKind = "UNKNOWN"
	PlatformKindVirtualMachineImage PlatformKind = "VIRTUAL_MACHINE_IMAGE"
	PlatformKindContainerImage      PlatformKind = "CONTAINER_IMAGE"
	PlatformKindCode                PlatformKind = "CODE"
	PlatformKindPackage             PlatformKind = "PACKAGE"
	PlatformKindVirtualMachine      PlatformKind = "VIRTUAL_MACHINE"
	PlatformKindContainer           PlatformKind = "CONTAINER"
	PlatformKindProcess             PlatformKind = "PROCESS"
	PlatformKindApi                 PlatformKind = "API"
	PlatformKindBareMetal           PlatformKind = "BARE_METAL"
)

// PolicyAction represents policy action.
type PolicyAction string

// Policy action.
const (
	PolicyActionActive PolicyAction = "ACTIVE"
	PolicyActionIgnore PolicyAction = "IGNORE"
)

// PolicyReportEntryState represents policy report entry state.
type PolicyReportEntryState string

// Policy report entry state.
const (
	PolicyReportEntryStatePass   PolicyReportEntryState = "PASS"
	PolicyReportEntryStateFail   PolicyReportEntryState = "FAIL"
	PolicyReportEntryStateIgnore PolicyReportEntryState = "IGNORE"
	PolicyReportEntryStateError  PolicyReportEntryState = "ERROR"
)

// PolicyReportMquerySummaryOrderField represents policy report mquery summary order field.
type PolicyReportMquerySummaryOrderField string

// Policy report mquery summary order field.
const (
	PolicyReportMquerySummaryOrderFieldId          PolicyReportMquerySummaryOrderField = "ID"
	PolicyReportMquerySummaryOrderFieldName        PolicyReportMquerySummaryOrderField = "NAME"
	PolicyReportMquerySummaryOrderFieldTitle       PolicyReportMquerySummaryOrderField = "TITLE"
	PolicyReportMquerySummaryOrderFieldPlatform    PolicyReportMquerySummaryOrderField = "PLATFORM"
	PolicyReportMquerySummaryOrderFieldScore       PolicyReportMquerySummaryOrderField = "SCORE"
	PolicyReportMquerySummaryOrderFieldLastUpdated PolicyReportMquerySummaryOrderField = "LAST_UPDATED"
)

// PolicyReportScoreEntryAction represents policy report score entry action.
type PolicyReportScoreEntryAction string

// Policy report score entry action.
const (
	PolicyReportScoreEntryActionUnspecified PolicyReportScoreEntryAction = "UNSPECIFIED"
	PolicyReportScoreEntryActionIgnore      PolicyReportScoreEntryAction = "IGNORE"
	PolicyReportScoreEntryActionDeactivate  PolicyReportScoreEntryAction = "DEACTIVATE"
)

// PolicyReportSummaryOrderField represents policy report summary order field.
type PolicyReportSummaryOrderField string

// Policy report summary order field.
const (
	PolicyReportSummaryOrderFieldId        PolicyReportSummaryOrderField = "ID"
	PolicyReportSummaryOrderFieldTitle     PolicyReportSummaryOrderField = "TITLE"
	PolicyReportSummaryOrderFieldPublished PolicyReportSummaryOrderField = "PUBLISHED"
	PolicyReportSummaryOrderFieldModified  PolicyReportSummaryOrderField = "MODIFIED"
	PolicyReportSummaryOrderFieldScore     PolicyReportSummaryOrderField = "SCORE"
)

// PropertyQueryMutationAction represents property query mutation action.
type PropertyQueryMutationAction string

// Property query mutation action.
const (
	PropertyQueryMutationActionSet   PropertyQueryMutationAction = "SET"   // If the set action is used, the existing property MQL will be overridden.
	PropertyQueryMutationActionCheck PropertyQueryMutationAction = "CHECK" // If the check action is used, the mutation will not take effect. We will attempt to validate the target and check the mql.
	PropertyQueryMutationActionUnset PropertyQueryMutationAction = "UNSET" // If a property override is set for the property mrn, the UNSET action will remove it.
)

// QueryImpact represents queryImpact maps an impact number to a human readable string.
type QueryImpact string

// QueryImpact maps an impact number to a human readable string.
const (
	QueryImpactCritical QueryImpact = "CRITICAL" // Impact is critical when 90 - 100.
	QueryImpactHigh     QueryImpact = "HIGH"     // Impact is high when between 70 - 89.
	QueryImpactMedium   QueryImpact = "MEDIUM"   // Impact is medium when between 40 - 69.
	QueryImpactLow      QueryImpact = "LOW"      // Impact is low when between 1 - 39.
	QueryImpactInfo     QueryImpact = "INFO"     // Impact is none when 0.
)

// RegistrationTokenOrderField represents field to order registration tokens by.
type RegistrationTokenOrderField string

// Field to order registration tokens by.
const (
	RegistrationTokenOrderFieldCreated     RegistrationTokenOrderField = "CREATED"     // Order by creation time.
	RegistrationTokenOrderFieldDescription RegistrationTokenOrderField = "DESCRIPTION" // Order by description.
	RegistrationTokenOrderFieldMrn         RegistrationTokenOrderField = "MRN"         // Order by MRN.
)

// RemediationScriptType represents remediation script type.
type RemediationScriptType string

// Remediation script type.
const (
	RemediationScriptTypeShell      RemediationScriptType = "SHELL"      // Shell script.
	RemediationScriptTypeAnsible    RemediationScriptType = "ANSIBLE"    // Ansible playbook.
	RemediationScriptTypePowershell RemediationScriptType = "POWERSHELL" // Powershell script.
)

// ReportViewedPage represents report viewed page defines the pages that can be reported as viewed.
type ReportViewedPage string

// Report viewed page defines the pages that can be reported as viewed.
const (
	ReportViewedPageOrgView                ReportViewedPage = "ORG_VIEW"
	ReportViewedPageAssetOverview          ReportViewedPage = "ASSET_OVERVIEW"
	ReportViewedPageCicdProject            ReportViewedPage = "CICD_PROJECT"
	ReportViewedPageCicdJob                ReportViewedPage = "CICD_JOB"
	ReportViewedPageVulnerabilityDashboard ReportViewedPage = "VULNERABILITY_DASHBOARD"
	ReportViewedPageSecurityDashboard      ReportViewedPage = "SECURITY_DASHBOARD"
)

// ReviewStatus represents the review status for an exception group.
type ReviewStatus string

// The review status for an exception group.
const (
	ReviewStatusNotReviewed      ReviewStatus = "NOT_REVIEWED"
	ReviewStatusApproved         ReviewStatus = "APPROVED"
	ReviewStatusRejected         ReviewStatus = "REJECTED"
	ReviewStatusPendingExtension ReviewStatus = "PENDING_EXTENSION"
)

// RiskFactorAction represents risk factor action.
type RiskFactorAction string

// Risk factor action.
const (
	RiskFactorActionEnable  RiskFactorAction = "ENABLE"  // Enable risk factor.
	RiskFactorActionDisable RiskFactorAction = "DISABLE" // Disable risk factor.
)

// RiskMagnitudeExplaination represents risk magnitude explanation.
type RiskMagnitudeExplaination string

// Risk magnitude explanation.
const (
	RiskMagnitudeExplainationIncreasesRisk RiskMagnitudeExplaination = "INCREASES_RISK"
	RiskMagnitudeExplainationDecreasesRisk RiskMagnitudeExplaination = "DECREASES_RISK"
	RiskMagnitudeExplainationNoEffect      RiskMagnitudeExplaination = "NO_EFFECT"
)

// ScoreRating represents score rating.
type ScoreRating string

// Score rating.
const (
	ScoreRatingCritical ScoreRating = "CRITICAL" // Critical - 0-10.
	ScoreRatingHigh     ScoreRating = "HIGH"     // High - 11-30.
	ScoreRatingMedium   ScoreRating = "MEDIUM"   // Medium - 31-60.
	ScoreRatingLow      ScoreRating = "LOW"      // Low - 61-99.
	ScoreRatingNone     ScoreRating = "NONE"     // None - 100.
	ScoreRatingUnscored ScoreRating = "UNSCORED" // Unscored, no scan ran yet.
)

// ScoreResultType represents score result type.
type ScoreResultType string

// Score result type.
const (
	ScoreResultTypeUnknown  ScoreResultType = "UNKNOWN"  // Was not scored for an unknown reason.
	ScoreResultTypeResult   ScoreResultType = "RESULT"   // Score represents a result.
	ScoreResultTypeError    ScoreResultType = "ERROR"    // Score rrepresents an error.
	ScoreResultTypeSkipped  ScoreResultType = "SKIPPED"  // Score was not scored because query was skipped.
	ScoreResultTypeUnscored ScoreResultType = "UNSCORED" // The query has no scoring element.
)

// ScoreSeverity represents scoreSeverity maps a score number to a severity level.
type ScoreSeverity string

// ScoreSeverity maps a score number to a severity level.
const (
	ScoreSeverityCritical ScoreSeverity = "CRITICAL" // Severity is critical when score is 0.
	ScoreSeverityHigh     ScoreSeverity = "HIGH"     // Severity is high when score is between 1 - 40.
	ScoreSeverityMedium   ScoreSeverity = "MEDIUM"   // Severity is medium when score is between 41 - 70.
	ScoreSeverityLow      ScoreSeverity = "LOW"      // Severity is low when score is between 71 - 90.
	ScoreSeverityNone     ScoreSeverity = "NONE"     // Severity is none when score is between 91 - 100.
)

// ScoreState represents score state.
type ScoreState string

// Score state.
const (
	ScoreStateOpen          ScoreState = "OPEN"           // Fixed/Pass.
	ScoreStateClosed        ScoreState = "CLOSED"         // Not fixed/Failed.
	ScoreStateSnoozed       ScoreState = "SNOOZED"        // Snoozed.
	ScoreStateDisabled      ScoreState = "DISABLED"       // Disabled.
	ScoreStateRiskAccepted  ScoreState = "RISK_ACCEPTED"  // Risk Accepted.
	ScoreStateWorkaround    ScoreState = "WORKAROUND"     // Workaround.
	ScoreStateFalsePositive ScoreState = "FALSE_POSITIVE" // False Positive.
)

// ScoreStateFilter represents score state filter.
type ScoreStateFilter string

// Score state filter.
const (
	ScoreStateFilterAll    ScoreStateFilter = "ALL"    // All.
	ScoreStateFilterOpen   ScoreStateFilter = "OPEN"   // Only not fixed/failed.
	ScoreStateFilterClosed ScoreStateFilter = "CLOSED" // Only fixed/passed.
)

// ScoreType represents score type.
type ScoreType string

// Score type.
const (
	ScoreTypeUnknown    ScoreType = "UNKNOWN"
	ScoreTypeResult     ScoreType = "RESULT"
	ScoreTypeError      ScoreType = "ERROR"
	ScoreTypeUnscored   ScoreType = "UNSCORED"
	ScoreTypeOutOfScope ScoreType = "OUT_OF_SCOPE"
	ScoreTypeDisabled   ScoreType = "DISABLED"
)

// ScoringSystem represents policy Scoring System.
type ScoringSystem string

// Policy Scoring System.
const (
	ScoringSystemAverage         ScoringSystem = "AVERAGE"
	ScoringSystemWeightedAverage ScoringSystem = "WEIGHTED_AVERAGE"
	ScoringSystemBanded          ScoringSystem = "BANDED"
	ScoringSystemDecayed         ScoringSystem = "DECAYED"
	ScoringSystemHighestImpact   ScoringSystem = "HIGHEST_IMPACT"
)

// SearchItemStatus represents status of the search item. Only applies to CVEs.
type SearchItemStatus string

// Status of the search item. Only applies to CVEs.
const (
	SearchItemStatusAffected    SearchItemStatus = "AFFECTED"
	SearchItemStatusNotAffected SearchItemStatus = "NOT_AFFECTED"
	SearchItemStatusUnsupported SearchItemStatus = "UNSUPPORTED"
)

// SearchType represents possible search types for the search query.
type SearchType string

// Possible search types for the search query.
const (
	SearchTypeAggregateScore SearchType = "AGGREGATE_SCORE" // Returns matching aggregate scores.
	SearchTypeMvd            SearchType = "MVD"             // Returns matching vulnerabilities and advisories in MVD.
	SearchTypeMvdV2          SearchType = "MVD_V2"          // Returns matching osv vulnerabilities in MVD V2.
)

// SecurityPipelineScheduledWorkflowCadence represents security pipeline scheduled workflow cadence.
type SecurityPipelineScheduledWorkflowCadence string

// Security pipeline scheduled workflow cadence.
const (
	SecurityPipelineScheduledWorkflowCadenceDaily   SecurityPipelineScheduledWorkflowCadence = "DAILY"
	SecurityPipelineScheduledWorkflowCadenceWeekly  SecurityPipelineScheduledWorkflowCadence = "WEEKLY"
	SecurityPipelineScheduledWorkflowCadenceMonthly SecurityPipelineScheduledWorkflowCadence = "MONTHLY"
)

// SecurityPipelineWorkflowOrderField represents security pipeline workflow order field.
type SecurityPipelineWorkflowOrderField string

// Security pipeline workflow order field.
const (
	SecurityPipelineWorkflowOrderFieldCreatedAt SecurityPipelineWorkflowOrderField = "CREATED_AT"
	SecurityPipelineWorkflowOrderFieldUpdatedAt SecurityPipelineWorkflowOrderField = "UPDATED_AT"
	SecurityPipelineWorkflowOrderFieldTitle     SecurityPipelineWorkflowOrderField = "TITLE"
)

// ServiceAccountOrderField represents field to order service accounts by.
type ServiceAccountOrderField string

// Field to order service accounts by.
const (
	ServiceAccountOrderFieldId        ServiceAccountOrderField = "ID"         // Order by ID.
	ServiceAccountOrderFieldName      ServiceAccountOrderField = "NAME"       // Order by name.
	ServiceAccountOrderFieldLastUsed  ServiceAccountOrderField = "LAST_USED"  // Order by last used time.
	ServiceAccountOrderFieldCreatedAt ServiceAccountOrderField = "CREATED_AT" // Order by creation time.
)

// Severity represents possible severities.
type Severity string

// Possible severities.
const (
	SeverityCritical Severity = "CRITICAL"
	SeverityHigh     Severity = "HIGH"
	SeverityMedium   Severity = "MEDIUM"
	SeverityLow      Severity = "LOW"
	SeverityNone     Severity = "NONE"
)

// TicketRefType represents ticket reference type.
type TicketRefType string

// Ticket reference type.
const (
	TicketRefTypeUnknown     TicketRefType = "UNKNOWN"
	TicketRefTypeJira        TicketRefType = "JIRA"
	TicketRefTypeEmail       TicketRefType = "EMAIL"
	TicketRefTypeZendesk     TicketRefType = "ZENDESK"
	TicketRefTypeGithub      TicketRefType = "GITHUB"
	TicketRefTypeGitlab      TicketRefType = "GITLAB"
	TicketRefTypeAzureDevops TicketRefType = "AZURE_DEVOPS"
	TicketRefTypeWebhook     TicketRefType = "WEBHOOK"
)

// TrustLevel represents trust level of the object.
type TrustLevel string

// Trust level of the object.
const (
	TrustLevelAll               TrustLevel = "ALL"
	TrustLevelOfficial          TrustLevel = "OFFICIAL"
	TrustLevelVerifiedPublisher TrustLevel = "VERIFIED_PUBLISHER"
	TrustLevelOss               TrustLevel = "OSS"
	TrustLevelPrivate           TrustLevel = "PRIVATE"
)

// UserState represents state of a user.
type UserState string

// State of a user.
const (
	UserStateUnknown    UserState = "UNKNOWN"
	UserStateWaitlisted UserState = "WAITLISTED"
	UserStateEnabled    UserState = "ENABLED"
)

// VPCFlavour represents describes flavour of the VPC for AWS Serverless Scanners.
type VPCFlavour string

// Describes flavour of the VPC for AWS Serverless Scanners.
const (
	VPCFlavourDefaultVpc  VPCFlavour = "DEFAULT_VPC"
	VPCFlavourMondooNatgw VPCFlavour = "MONDOO_NATGW"
	VPCFlavourMondooIgw   VPCFlavour = "MONDOO_IGW"
	VPCFlavourCustomVpc   VPCFlavour = "CUSTOM_VPC"
)

// VulnerabilityOrderType represents possible vulnerability order types.
type VulnerabilityOrderType string

// possible vulnerability order types.
const (
	VulnerabilityOrderTypeNewest VulnerabilityOrderType = "NEWEST"
	VulnerabilityOrderTypeSevere VulnerabilityOrderType = "SEVERE"
)

// VulnerabilityScoreSourceVendor represents vendor that can source a vulnerability.
type VulnerabilityScoreSourceVendor string

// Vendor that can source a vulnerability.
const (
	VulnerabilityScoreSourceVendorUnknown     VulnerabilityScoreSourceVendor = "UNKNOWN"
	VulnerabilityScoreSourceVendorMondoo      VulnerabilityScoreSourceVendor = "MONDOO"
	VulnerabilityScoreSourceVendorMicrosoft   VulnerabilityScoreSourceVendor = "MICROSOFT"
	VulnerabilityScoreSourceVendorCrowdstrike VulnerabilityScoreSourceVendor = "CROWDSTRIKE"
	VulnerabilityScoreSourceVendorSentinelOne VulnerabilityScoreSourceVendor = "SENTINEL_ONE"
)

// WorkflowRefMethod represents workflow reference method. This indicates how the reference was added to the workflow.
type WorkflowRefMethod string

// Workflow reference method. This indicates how the reference was added to the workflow.
const (
	WorkflowRefMethodSelected WorkflowRefMethod = "SELECTED" // The reference was selected when the workflow got created.
	WorkflowRefMethodRelated  WorkflowRefMethod = "RELATED"  // The reference was added because it would implicitly be fixed when all selected references are fixed.
)

// WorkflowStatus represents workflow status.
type WorkflowStatus string

// Workflow status.
const (
	WorkflowStatusPending   WorkflowStatus = "PENDING"
	WorkflowStatusPrCreated WorkflowStatus = "PR_CREATED"
	WorkflowStatusPrMerged  WorkflowStatus = "PR_MERGED"
	WorkflowStatusFixed     WorkflowStatus = "FIXED"
	WorkflowStatusCanceled  WorkflowStatus = "CANCELED"
	WorkflowStatusFailed    WorkflowStatus = "FAILED"
)

// WorkflowTaskStatus represents workflow task status.
type WorkflowTaskStatus string

// Workflow task status.
const (
	WorkflowTaskStatusPending    WorkflowTaskStatus = "PENDING"
	WorkflowTaskStatusInProgress WorkflowTaskStatus = "IN_PROGRESS"
	WorkflowTaskStatusCompleted  WorkflowTaskStatus = "COMPLETED"
	WorkflowTaskStatusCanceled   WorkflowTaskStatus = "CANCELED"
	WorkflowTaskStatusFailed     WorkflowTaskStatus = "FAILED"
)

// WorkflowTaskType represents workflow task type.
type WorkflowTaskType string

// Workflow task type.
const (
	WorkflowTaskTypeCreatePr   WorkflowTaskType = "CREATE_PR"
	WorkflowTaskTypeClosePr    WorkflowTaskType = "CLOSE_PR"
	WorkflowTaskTypeConfirmFix WorkflowTaskType = "CONFIRM_FIX"
)

// WorkspaceSelectionConditionIntField represents workspace selection condition int fields.
type WorkspaceSelectionConditionIntField string

// Workspace selection condition int fields.
const (
	WorkspaceSelectionConditionIntFieldUnknown   WorkspaceSelectionConditionIntField = "UNKNOWN"    // Unknwon int field.
	WorkspaceSelectionConditionIntFieldRiskScore WorkspaceSelectionConditionIntField = "RISK_SCORE" // Risk score field.
)

// WorkspaceSelectionConditionKeyValueField represents workspace selection condition key-value fields.
type WorkspaceSelectionConditionKeyValueField string

// Workspace selection condition key-value fields.
const (
	WorkspaceSelectionConditionKeyValueFieldUnknown     WorkspaceSelectionConditionKeyValueField = "UNKNOWN"     // Unknwon key-value field.
	WorkspaceSelectionConditionKeyValueFieldLabels      WorkspaceSelectionConditionKeyValueField = "LABELS"      // Labels field.
	WorkspaceSelectionConditionKeyValueFieldAnnotations WorkspaceSelectionConditionKeyValueField = "ANNOTATIONS" // Annotations field.
)

// WorkspaceSelectionConditionKeyValueOperator represents workspace selection condition key-value operators.
type WorkspaceSelectionConditionKeyValueOperator string

// Workspace selection condition key-value operators.
const (
	WorkspaceSelectionConditionKeyValueOperatorUnknown     WorkspaceSelectionConditionKeyValueOperator = "UNKNOWN"      // Unknown operator.
	WorkspaceSelectionConditionKeyValueOperatorContains    WorkspaceSelectionConditionKeyValueOperator = "CONTAINS"     // Contains operator.
	WorkspaceSelectionConditionKeyValueOperatorNotContains WorkspaceSelectionConditionKeyValueOperator = "NOT_CONTAINS" // Does not contain operator.
)

// WorkspaceSelectionConditionNumericOperator represents workspace selection condition string operators.
type WorkspaceSelectionConditionNumericOperator string

// Workspace selection condition string operators.
const (
	WorkspaceSelectionConditionNumericOperatorUnknown  WorkspaceSelectionConditionNumericOperator = "UNKNOWN"   // Unknown operator.
	WorkspaceSelectionConditionNumericOperatorEqual    WorkspaceSelectionConditionNumericOperator = "EQUAL"     // Equal operator.
	WorkspaceSelectionConditionNumericOperatorNotEqual WorkspaceSelectionConditionNumericOperator = "NOT_EQUAL" // Not equal operator.
	WorkspaceSelectionConditionNumericOperatorGt       WorkspaceSelectionConditionNumericOperator = "GT"        // Greater than operator.
	WorkspaceSelectionConditionNumericOperatorLt       WorkspaceSelectionConditionNumericOperator = "LT"        // Less than operator.
)

// WorkspaceSelectionConditionOperator represents workspace selection condition operator.
type WorkspaceSelectionConditionOperator string

// Workspace selection condition operator.
const (
	WorkspaceSelectionConditionOperatorUnknown WorkspaceSelectionConditionOperator = "UNKNOWN" // Unknown operator.
	WorkspaceSelectionConditionOperatorAnd     WorkspaceSelectionConditionOperator = "AND"     // AND operator, meaning the condition will be "ANDed" to other conditions.
	WorkspaceSelectionConditionOperatorAndNot  WorkspaceSelectionConditionOperator = "AND_NOT" // AND NOT operator, meaning the condition will be "ANDed" to other conditions with a NOT.
)

// WorkspaceSelectionConditionRatingField represents workspace selection condition rating fields.
type WorkspaceSelectionConditionRatingField string

// Workspace selection condition rating fields.
const (
	WorkspaceSelectionConditionRatingFieldUnknown WorkspaceSelectionConditionRatingField = "UNKNOWN" // Unknwon rating field.
	WorkspaceSelectionConditionRatingFieldRisk    WorkspaceSelectionConditionRatingField = "RISK"    // Risk field.
)

// WorkspaceSelectionConditionRatingOperator represents workspace selection condition rating operators.
type WorkspaceSelectionConditionRatingOperator string

// Workspace selection condition rating operators.
const (
	WorkspaceSelectionConditionRatingOperatorUnknown  WorkspaceSelectionConditionRatingOperator = "UNKNOWN"   // Unknown operator.
	WorkspaceSelectionConditionRatingOperatorEqual    WorkspaceSelectionConditionRatingOperator = "EQUAL"     // Equal operator.
	WorkspaceSelectionConditionRatingOperatorNotEqual WorkspaceSelectionConditionRatingOperator = "NOT_EQUAL" // Not equal operator.
)

// WorkspaceSelectionConditionStringField represents workspace selection condition string fields.
type WorkspaceSelectionConditionStringField string

// Workspace selection condition string fields.
const (
	WorkspaceSelectionConditionStringFieldUnknown         WorkspaceSelectionConditionStringField = "UNKNOWN"          // Unknwon string field.
	WorkspaceSelectionConditionStringFieldPlatform        WorkspaceSelectionConditionStringField = "PLATFORM"         // Platform field.
	WorkspaceSelectionConditionStringFieldPlatformVersion WorkspaceSelectionConditionStringField = "PLATFORM_VERSION" // Platform version field.
	WorkspaceSelectionConditionStringFieldAssetName       WorkspaceSelectionConditionStringField = "ASSET_NAME"       // Asset name field.
	WorkspaceSelectionConditionStringFieldAssetKind       WorkspaceSelectionConditionStringField = "ASSET_KIND"       // Asset kind field.
	WorkspaceSelectionConditionStringFieldTechnology      WorkspaceSelectionConditionStringField = "TECHNOLOGY"       // Technology field.
)

// WorkspaceSelectionConditionStringOperator represents workspace selection condition string operators.
type WorkspaceSelectionConditionStringOperator string

// Workspace selection condition string operators.
const (
	WorkspaceSelectionConditionStringOperatorUnknown  WorkspaceSelectionConditionStringOperator = "UNKNOWN"   // Unknown operator.
	WorkspaceSelectionConditionStringOperatorEqual    WorkspaceSelectionConditionStringOperator = "EQUAL"     // Equal operator.
	WorkspaceSelectionConditionStringOperatorNotEqual WorkspaceSelectionConditionStringOperator = "NOT_EQUAL" // Not equal operator.
	WorkspaceSelectionConditionStringOperatorContains WorkspaceSelectionConditionStringOperator = "CONTAINS"  // Contains operator.
)

// ZendeskTicketContextType represents the type of the ticket context.
type ZendeskTicketContextType string

// The type of the ticket context.
const (
	ZendeskTicketContextTypeFields ZendeskTicketContextType = "FIELDS" // The ticket context for Zendesk projects.
)
